import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'addSound': 'Add Sound',
      'addSoundDesc': 'Add custom sounds to your soundboard',
      'loop': 'Loop',
      'shufflePlay': 'Shuffle Play',
      'playbackSpeed': 'Playback Speed',
      'deleteMode': 'Delete mode',
      'cancelDeleteMode': 'Cancel delete mode',
      'searchSounds': 'Search sounds...',
      'noSoundPlaying': 'No sound playing',
      'nowPlaying': 'Now playing:',
      'soundsCount': 'sounds',
      'noSoundsFound': 'No sounds found',
      'tryChangingSearch': 'Try changing your search or category',
      'restoringSound': 'Restoring sounds...',
      'pleaseWait': 'Please wait a moment',
      'resetSounds': 'Reset Sounds',
      'resetSoundsDescription': 'This will delete all current sounds and reload the original sounds with their categories.',
      'resetToDefault': 'Reset to default sounds',
      'resetConfirmTitle': 'Reset sounds',
      'resetConfirmMessage': 'This will delete all current sounds and reload the original sounds with their categories.\n\nDo you want to continue?',
      'cancel': 'Cancel',
      'reset': 'Reset',
      'deleteAll': 'Delete All',
      'deleteAllSounds': 'Delete all sounds',
      'deleteAllConfirmTitle': 'Delete all sounds',
      'deleteAllConfirmMessage': 'This will permanently delete all sounds. This cannot be undone.\n\nDo you want to continue?',
      'manageCategories': 'Manage Categories',
      'manageCategoriesDescription': 'Delete categories that you no longer need. All sounds with this category will lose it.',
      'trimSound': 'Trim sound',
      'trimReset': 'Reset trim',
      'trimLoading': 'Loading...',
      'editCategory': 'Edit category',
      'newCategoryName': 'New name',
      'deleteCategory': 'Delete category',
      'deleteCategoryConfirm': 'Are you sure you want to delete "{category}"?\n\nAll sounds with this category will lose it.',
      'deleteSoundsAlso': 'Also delete all sounds with this category',
      'delete': 'Delete',
      'noCustomCategories': 'No custom categories yet',
      'language': 'Language',
      'selectLanguage': 'Select your preferred language',
      'soundName': 'Sound name',
      'categories': 'Categories',
      'add': 'Add',
      'newCategory': 'New category',
      'enterCategoryName': 'Enter category name',
      'buttonColor': 'Button color',
      'save': 'Save',
      'addNewSound': 'Add new sound',
      'categoryName': 'Category name',
      'stopRecording': 'Stop recording',
      'record': 'Record',
      'play': 'Play',
      'stop': 'Stop',
      'pickFile': 'Pick file',
      'addCategory': 'Add category',
      'saveSound': 'Save sound',
      'filter': 'Filter:',
      'search': 'Search:',
      'soundsOnlyInEverything': 'sounds have no category and will only appear in Everything',
      'errorDeletingSound': 'Error deleting sound:',
      'errorPlayingSound': 'Error playing sound:',
      'fileNotExist': 'File does not exist in storage',
      'speed05': '0.5x Speed',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Speed',
      'privacySettings': 'Privacy Settings',
      'privacySettingsDesc': 'Manage your ad personalization preferences',
      'managePrivacy': 'Manage Privacy',
      'volume': 'Volume',
      'everything': 'Everything',
      'favorite': 'Favorite',
      'simpleMode': 'Simple Mode',
      'simpleModeDesc': 'Hide settings and favourite buttons on each sound',
      'hideCategories': 'Hide categories',
      'hidePlayback': 'Hide playback bar',
      'hapticFeedback': 'Vibration',
      'backupRestore': 'Backup & Restore',
      'backupRestoreDesc': 'Export your sounds to a file or restore from a previous backup.',
      'exportSounds': 'Export sounds',
      'importSounds': 'Import sounds',
      'toolbarButtons': 'Toolbar Buttons',
      'toolbarButtonsDesc': 'Choose which buttons appear in the top toolbar',
      'darkMode': 'Dark Mode',
      'supportTitle': 'Support the Developer',
      'supportDesc': 'If you enjoy the app, consider buying me a coffee!',
      'donateButton': 'Buy me a coffee',
      'noCategoryTitle': 'No category selected',
      'noCategoryMessage': 'This sound will only appear in "Everything". Add anyway?',
      'addAnyway': 'Add anyway',
      'volumeControl': 'Volume control',
      'displayOptions': 'Display Options',
      'displayOptionsDesc': 'Choose what to show on the soundboard',
      'hideFavoriteButton': 'Hide favorite button',
      'hideSettingsButton': 'Hide settings button',
      'fadeGlobalDescription': 'Global setting for all sounds',
    },
    'sk': {
      'settings': 'Nastavenia',
      'addSound': 'Pridať zvuk',
      'addSoundDesc': 'Pridať vlastné zvuky do soundboardu',
      'loop': 'Opakovať',
      'shufflePlay': 'Náhodné prehrávanie',
      'playbackSpeed': 'Rýchlosť prehrávania',
      'deleteMode': 'Režim mazania',
      'cancelDeleteMode': 'Zrušiť režim mazania',
      'searchSounds': 'Hľadať zvuky...',
      'noSoundPlaying': 'Žiadny zvuk sa neprehráva',
      'nowPlaying': 'Práve hrá:',
      'soundsCount': 'zvukov',
      'noSoundsFound': 'Nenašli sa žiadne zvuky',
      'tryChangingSearch': 'Skúste zmeniť vyhľadávanie alebo kategóriu',
      'restoringSound': 'Obnovujem zvuky...',
      'pleaseWait': 'Prosím počkajte chvíľu',
      'resetSounds': 'Resetovať zvuky',
      'resetSoundsDescription': 'Toto vymaže všetky aktuálne zvuky a obnoví pôvodné zvuky s ich kategóriami.',
      'resetToDefault': 'Resetovať na predvolené zvuky',
      'resetConfirmTitle': 'Resetovať zvuky',
      'resetConfirmMessage': 'Toto vymaže všetky aktuálne zvuky a obnoví pôvodné zvuky s ich kategóriami.\n\nChcete pokračovať?',
      'cancel': 'Zrušiť',
      'reset': 'Resetovať',
      'deleteAll': 'Vymazať všetko',
      'deleteAllSounds': 'Vymazať všetky zvuky',
      'deleteAllConfirmTitle': 'Vymazať všetky zvuky',
      'deleteAllConfirmMessage': 'Toto natrvalo vymaže všetky zvuky. Akciu nie je možné vrátiť.\n\nChcete pokračovať?',
      'manageCategories': 'Spravovať kategórie',
      'manageCategoriesDescription': 'Vymažte kategórie, ktoré už nepotrebujete. Všetky zvuky s touto kategóriou ju stratia.',
      'trimSound': 'Orezať zvuk',
      'trimReset': 'Resetovať orez',
      'trimLoading': 'Načítavam...',
      'editCategory': 'Upraviť kategóriu',
      'newCategoryName': 'Nový názov',
      'deleteCategory': 'Vymazať kategóriu',
      'deleteCategoryConfirm': 'Naozaj chcete vymazať "{category}"?\n\nVšetky zvuky s touto kategóriou ju stratia.',
      'deleteSoundsAlso': 'Vymazať aj všetky zvuky s touto kategóriou',
      'delete': 'Vymazať',
      'noCustomCategories': 'Zatiaľ žiadne vlastné kategórie',
      'language': 'Jazyk',
      'selectLanguage': 'Vyberte si preferovaný jazyk',
      'soundName': 'Názov zvuku',
      'categories': 'Kategórie',
      'add': 'Pridať',
      'newCategory': 'Nová kategória',
      'enterCategoryName': 'Zadajte názov kategórie',
      'buttonColor': 'Farba tlačidla',
      'save': 'Uložiť',
      'addNewSound': 'Pridať nový zvuk',
      'categoryName': 'Názov kategórie',
      'stopRecording': 'Zastaviť nahrávanie',
      'record': 'Nahrať',
      'play': 'Prehrať',
      'stop': 'Zastaviť',
      'pickFile': 'Vybrať súbor',
      'addCategory': 'Pridať kategóriu',
      'saveSound': 'Uložiť zvuk',
      'filter': 'Filter:',
      'search': 'Hľadať:',
      'soundsOnlyInEverything': 'zvukov nemá kategóriu a bude viditeľných iba v Všetko',
      'errorDeletingSound': 'Chyba pri mazaní zvuku:',
      'errorPlayingSound': 'Chyba pri prehrávaní zvuku:',
      'fileNotExist': 'Súbor neexistuje v úložisku',
      'speed05': '0.5x Rýchlosť',
      'speed10': '1.0x Normálna',
      'speed20': '2.0x Rýchlosť',
      'privacySettings': 'Nastavenia súkromia',
      'privacySettingsDesc': 'Spravujte svoje preferencie personalizácie reklám',
      'managePrivacy': 'Spravovať súkromie',
      'volume': 'Hlasitosť',
      'everything': 'Všetko',
      'favorite': 'Obľúbené',
      'simpleMode': 'Jednoduchý režim',
      'simpleModeDesc': 'Skryť tlačidlá nastavení a obľúbených na každom zvuku',
      'hideCategories': 'Skryť kategórie',
      'hidePlayback': 'Skryť prehrávač',
      'volumeControl': 'Ovládač hlasitosti',
      'displayOptions': 'Možnosti zobrazenia',
      'displayOptionsDesc': 'Vyberte, čo sa zobrazí na soundboarde',
      'hideFavoriteButton': 'Skryť tlačidlo obľúbených',
      'hideSettingsButton': 'Skryť tlačidlo nastavení',
      'hapticFeedback': 'Vibrácia',
      'backupRestore': 'Záloha a obnovenie',
      'backupRestoreDesc': 'Exportujte zvuky do súboru alebo obnovte zo zálohy.',
      'exportSounds': 'Exportovať zvuky',
      'importSounds': 'Importovať zvuky',
      'toolbarButtons': 'Tlačidlá panela nástrojov',
      'toolbarButtonsDesc': 'Vyberte, ktoré tlačidlá sa zobrazia v hornom paneli',
      'darkMode': 'Tmavý režim',
      'supportTitle': 'Podporte vývojára',
      'supportDesc': 'Ak sa vám appka páči, môžete mi kúpiť kávu!',
      'donateButton': 'Kúpiť kávu',
      'noCategoryTitle': 'Žiadna kategória',
      'noCategoryMessage': 'Tento zvuk sa zobrazí len v „Všetko". Pridať aj tak?',
      'addAnyway': 'Pridať aj tak',
      'fadeGlobalDescription': 'Globálne nastavenie pre všetky zvuky',
    },
    'es': {
      'settings': 'Configuración',
      'addSound': 'Agregar sonido',
      'addSoundDesc': 'Agregar sonidos personalizados a tu soundboard',
      'loop': 'Repetir',
      'shufflePlay': 'Reproducción aleatoria',
      'playbackSpeed': 'Velocidad de reproducción',
      'deleteMode': 'Modo de eliminación',
      'cancelDeleteMode': 'Cancelar modo de eliminación',
      'searchSounds': 'Buscar sonidos...',
      'noSoundPlaying': 'No hay sonido reproduciéndose',
      'nowPlaying': 'Reproduciendo:',
      'soundsCount': 'sonidos',
      'noSoundsFound': 'No se encontraron sonidos',
      'tryChangingSearch': 'Intenta cambiar tu búsqueda o categoría',
      'restoringSound': 'Restaurando sonidos...',
      'pleaseWait': 'Por favor espera un momento',
      'resetSounds': 'Restablecer sonidos',
      'resetSoundsDescription': 'Esto eliminará todos los sonidos actuales y recargará los sonidos originales con sus categorías.',
      'resetToDefault': 'Restablecer a sonidos predeterminados',
      'resetConfirmTitle': 'Restablecer sonidos',
      'resetConfirmMessage': 'Esto eliminará todos los sonidos actuales y recargará los sonidos originales con sus categorías.\n\n¿Deseas continuar?',
      'cancel': 'Cancelar',
      'reset': 'Restablecer',
      'deleteAll': 'Eliminar todo',
      'deleteAllSounds': 'Eliminar todos los sonidos',
      'deleteAllConfirmTitle': 'Eliminar todos los sonidos',
      'deleteAllConfirmMessage': 'Esto eliminará permanentemente todos los sonidos. No se puede deshacer.\n\n¿Desea continuar?',
      'manageCategories': 'Gestionar categorías',
      'manageCategoriesDescription': 'Elimina las categorías que ya no necesites. Todos los sonidos con esta categoría la perderán.',
      'trimSound': 'Recortar sonido',
      'trimReset': 'Restablecer recorte',
      'trimLoading': 'Cargando...',
      'editCategory': 'Editar categoría',
      'newCategoryName': 'Nuevo nombre',
      'deleteCategory': 'Eliminar categoría',
      'deleteCategoryConfirm': '¿Estás seguro de que deseas eliminar "{category}"?\n\nTodos los sonidos con esta categoría la perderán.',
      'deleteSoundsAlso': 'También eliminar todos los sonidos con esta categoría',
      'delete': 'Eliminar',
      'noCustomCategories': 'Aún no hay categorías personalizadas',
      'language': 'Idioma',
      'selectLanguage': 'Selecciona tu idioma preferido',
      'soundName': 'Nombre del sonido',
      'categories': 'Categorías',
      'add': 'Agregar',
      'newCategory': 'Nueva categoría',
      'enterCategoryName': 'Ingresa el nombre de la categoría',
      'buttonColor': 'Color del botón',
      'save': 'Guardar',
      'addNewSound': 'Agregar nuevo sonido',
      'categoryName': 'Nombre de categoría',
      'stopRecording': 'Detener grabación',
      'record': 'Grabar',
      'play': 'Reproducir',
      'stop': 'Detener',
      'pickFile': 'Seleccionar archivo',
      'addCategory': 'Agregar categoría',
      'saveSound': 'Guardar sonido',
      'filter': 'Filtro:',
      'search': 'Buscar:',
      'soundsOnlyInEverything': 'sonidos no tienen categoría y solo aparecerán en Todo',
      'errorDeletingSound': 'Error al eliminar sonido:',
      'errorPlayingSound': 'Error al reproducir sonido:',
      'fileNotExist': 'El archivo no existe en el almacenamiento',
      'speed05': '0.5x Velocidad',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Velocidad',
      'privacySettings': 'Configuración de privacidad',
      'privacySettingsDesc': 'Administra tus preferencias de personalización de anuncios',
      'managePrivacy': 'Gestionar privacidad',
      'volume': 'Volumen',
      'everything': 'Todo',
      'favorite': 'Favorito',
      'simpleMode': 'Modo simple',
      'simpleModeDesc': 'Ocultar los botones de ajustes y favoritos en cada sonido',
      'hideCategories': 'Ocultar categorías',
      'hidePlayback': 'Ocultar reproductor',
      'volumeControl': 'Control de volumen',
      'displayOptions': 'Opciones de pantalla',
      'displayOptionsDesc': 'Elige qué mostrar en el soundboard',
      'hideFavoriteButton': 'Ocultar botón de favoritos',
      'hideSettingsButton': 'Ocultar botón de ajustes',
      'hapticFeedback': 'Vibración',
      'backupRestore': 'Copia de seguridad',
      'backupRestoreDesc': 'Exporta tus sonidos o restaura desde una copia de seguridad.',
      'exportSounds': 'Exportar sonidos',
      'importSounds': 'Importar sonidos',
      'toolbarButtons': 'Botones de barra',
      'toolbarButtonsDesc': 'Elige qué botones aparecen en la barra superior',
      'darkMode': 'Modo oscuro',
      'supportTitle': 'Apoya al desarrollador',
      'supportDesc': '¡Si disfrutas la app, considera invitarme un café!',
      'donateButton': 'Invítame un café',
      'noCategoryTitle': 'Sin categoría',
      'noCategoryMessage': 'Este sonido solo aparecerá en "Todo". ¿Añadir de todas formas?',
      'addAnyway': 'Añadir de todas formas',
      'fadeGlobalDescription': 'Configuración global para todos los sonidos',
    },
    'fr': {
      'settings': 'Paramètres',
      'addSound': 'Ajouter un son',
      'addSoundDesc': 'Ajouter des sons personnalisés à votre soundboard',
      'loop': 'Répéter',
      'shufflePlay': 'Lecture aléatoire',
      'playbackSpeed': 'Vitesse de lecture',
      'deleteMode': 'Mode suppression',
      'cancelDeleteMode': 'Annuler le mode suppression',
      'searchSounds': 'Rechercher des sons...',
      'noSoundPlaying': 'Aucun son en cours',
      'nowPlaying': 'En cours :',
      'soundsCount': 'sons',
      'noSoundsFound': 'Aucun son trouvé',
      'tryChangingSearch': 'Modifiez votre recherche ou catégorie',
      'restoringSound': 'Restauration des sons...',
      'pleaseWait': 'Patientez un instant',
      'resetSounds': 'Réinitialiser les sons',
      'resetSoundsDescription': 'Cela supprimera tous les sons actuels et rechargera les sons originaux avec leurs catégories.',
      'resetToDefault': 'Réinitialiser aux sons par défaut',
      'resetConfirmTitle': 'Réinitialiser les sons',
      'resetConfirmMessage': 'Cela supprimera tous les sons actuels et rechargera les sons originaux avec leurs catégories.\n\nVoulez-vous continuer ?',
      'cancel': 'Annuler',
      'reset': 'Réinitialiser',
      'deleteAll': 'Tout supprimer',
      'deleteAllSounds': 'Supprimer tous les sons',
      'deleteAllConfirmTitle': 'Supprimer tous les sons',
      'deleteAllConfirmMessage': 'Cela supprimera définitivement tous les sons. Cette action est irréversible.\n\nVoulez-vous continuer?',
      'manageCategories': 'Gérer les catégories',
      'manageCategoriesDescription': 'Supprimez les catégories dont vous n\'avez plus besoin. Tous les sons de cette catégorie la perdront.',
      'trimSound': 'Rogner le son',
      'trimReset': 'Réinitialiser le rognage',
      'trimLoading': 'Chargement...',
      'editCategory': 'Modifier la catégorie',
      'newCategoryName': 'Nouveau nom',
      'deleteCategory': 'Supprimer la catégorie',
      'deleteCategoryConfirm': 'Êtes-vous sûr de vouloir supprimer "{category}" ?\n\nTous les sons de cette catégorie la perdront.',
      'deleteSoundsAlso': 'Supprimer aussi tous les sons de cette catégorie',
      'delete': 'Supprimer',
      'noCustomCategories': 'Aucune catégorie personnalisée pour l\'instant',
      'language': 'Langue',
      'selectLanguage': 'Sélectionnez votre langue préférée',
      'soundName': 'Nom du son',
      'categories': 'Catégories',
      'add': 'Ajouter',
      'newCategory': 'Nouvelle catégorie',
      'enterCategoryName': 'Entrez le nom de la catégorie',
      'buttonColor': 'Couleur du bouton',
      'save': 'Enregistrer',
      'addNewSound': 'Ajouter un nouveau son',
      'categoryName': 'Nom de la catégorie',
      'stopRecording': 'Arrêter l\'enregistrement',
      'record': 'Enregistrer',
      'play': 'Lire',
      'stop': 'Arrêter',
      'pickFile': 'Choisir un fichier',
      'addCategory': 'Ajouter une catégorie',
      'saveSound': 'Enregistrer le son',
      'filter': 'Filtrer',
      'search': 'Rechercher',
      'soundsOnlyInEverything': 'sons n\'ont pas de catégorie et n\'apparaîtront que dans Tout',
      'errorDeletingSound': 'Erreur lors de la suppression du son :',
      'errorPlayingSound': 'Erreur lors de la lecture du son :',
      'fileNotExist': 'Le fichier n\'existe pas dans le stockage',
      'speed05': '0.5x Vitesse',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Vitesse',
      'privacySettings': 'Paramètres de confidentialité',
      'privacySettingsDesc': 'Gérez vos préférences de personnalisation des publicités',
      'managePrivacy': 'Gérer la confidentialité',
      'volume': 'Volume',
      'everything': 'Tous',
      'favorite': 'Favori',
      'simpleMode': 'Mode simple',
      'simpleModeDesc': 'Masquer les boutons de réglages et favoris sur chaque son',
      'hideCategories': 'Masquer les catégories',
      'hidePlayback': 'Masquer le lecteur',
      'volumeControl': 'Contrôle du volume',
      'displayOptions': 'Options d\'affichage',
      'displayOptionsDesc': 'Choisissez ce qui s\'affiche sur le soundboard',
      'hideFavoriteButton': 'Masquer le bouton favori',
      'hideSettingsButton': 'Masquer le bouton réglages',
      'hapticFeedback': 'Vibration',
      'backupRestore': 'Sauvegarde et restauration',
      'backupRestoreDesc': 'Exportez vos sons ou restaurez depuis une sauvegarde.',
      'exportSounds': 'Exporter les sons',
      'importSounds': 'Importer les sons',
      'toolbarButtons': 'Boutons de barre',
      'toolbarButtonsDesc': 'Choisissez quels boutons apparaissent dans la barre supérieure',
      'darkMode': 'Mode sombre',
      'supportTitle': 'Soutenir le développeur',
      'supportDesc': 'Si vous aimez l\'app, offrez-moi un café !',
      'donateButton': 'Offrir un café',
      'noCategoryTitle': 'Aucune catégorie',
      'noCategoryMessage': 'Ce son apparaîtra uniquement dans « Tous ». Ajouter quand même ?',
      'addAnyway': 'Ajouter quand même',
      'fadeGlobalDescription': 'Paramètre global pour tous les sons',
    },
    'de': {
      'settings': 'Einstellungen',
      'addSound': 'Sound hinzufügen',
      'addSoundDesc': 'Eigene Sounds zum Soundboard hinzufügen',
      'loop': 'Wiederholen',
      'shufflePlay': 'Zufallswiedergabe',
      'playbackSpeed': 'Wiedergabegeschwindigkeit',
      'deleteMode': 'Löschmodus',
      'cancelDeleteMode': 'Löschmodus beenden',
      'searchSounds': 'Sounds suchen...',
      'noSoundPlaying': 'Kein Sound wird abgespielt',
      'nowPlaying': 'Läuft:',
      'soundsCount': 'Sounds',
      'noSoundsFound': 'Keine Sounds gefunden',
      'tryChangingSearch': 'Versuche, deine Suche oder Kategorie zu ändern',
      'restoringSound': 'Sounds werden wiederhergestellt...',
      'pleaseWait': 'Bitte einen Moment warten',
      'resetSounds': 'Sounds zurücksetzen',
      'resetSoundsDescription': 'Dies löscht alle aktuellen Sounds und lädt die Original-Sounds mit ihren Kategorien neu.',
      'resetToDefault': 'Auf Standard-Sounds zurücksetzen',
      'resetConfirmTitle': 'Sounds zurücksetzen',
      'resetConfirmMessage': 'Dies löscht alle aktuellen Sounds und lädt die Original-Sounds mit ihren Kategorien neu.\n\nMöchtest du fortfahren?',
      'cancel': 'Abbrechen',
      'reset': 'Zurücksetzen',
      'deleteAll': 'Alle löschen',
      'deleteAllSounds': 'Alle Sounds löschen',
      'deleteAllConfirmTitle': 'Alle Sounds löschen',
      'deleteAllConfirmMessage': 'Dies löscht alle Sounds dauerhaft. Dies kann nicht rückgängig gemacht werden.\n\nMöchten Sie fortfahren?',
      'manageCategories': 'Kategorien verwalten',
      'manageCategoriesDescription': 'Lösche Kategorien, die du nicht mehr benötigst. Alle Sounds mit dieser Kategorie verlieren sie.',
      'trimSound': 'Sound trimmen',
      'trimReset': 'Trim zurücksetzen',
      'trimLoading': 'Lädt...',
      'editCategory': 'Kategorie bearbeiten',
      'newCategoryName': 'Neuer Name',
      'deleteCategory': 'Kategorie löschen',
      'deleteCategoryConfirm': 'Bist du sicher, dass du "{category}" löschen möchtest?\n\nAlle Sounds mit dieser Kategorie verlieren sie.',
      'deleteSoundsAlso': 'Auch alle Sounds mit dieser Kategorie löschen',
      'delete': 'Löschen',
      'noCustomCategories': 'Noch keine eigenen Kategorien',
      'language': 'Sprache',
      'selectLanguage': 'Wähle deine bevorzugte Sprache',
      'soundName': 'Soundname',
      'categories': 'Kategorien',
      'add': 'Hinzufügen',
      'newCategory': 'Neue Kategorie',
      'enterCategoryName': 'Kategorienamen eingeben',
      'buttonColor': 'Buttonfarbe',
      'save': 'Speichern',
      'addNewSound': 'Neuen Sound hinzufügen',
      'categoryName': 'Kategoriename',
      'stopRecording': 'Aufnahme stoppen',
      'record': 'Aufnehmen',
      'play': 'Abspielen',
      'stop': 'Stoppen',
      'pickFile': 'Datei auswählen',
      'addCategory': 'Kategorie hinzufügen',
      'saveSound': 'Sound speichern',
      'filter': 'Filter:',
      'search': 'Suchen:',
      'soundsOnlyInEverything': 'Sounds haben keine Kategorie und erscheinen nur in Alles',
      'errorDeletingSound': 'Fehler beim Löschen:',
      'errorPlayingSound': 'Fehler beim Abspielen:',
      'fileNotExist': 'Datei nicht im Speicher gefunden',
      'speed05': '0.5x Langsam',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Schnell',
      'privacySettings': 'Datenschutzeinstellungen',
      'privacySettingsDesc': 'Präferenzen für personalisierte Werbung verwalten',
      'managePrivacy': 'Datenschutz verwalten',
      'volume': 'Lautstärke',
      'everything': 'Alles',
      'favorite': 'Favorit',
      'simpleMode': 'Einfacher Modus',
      'simpleModeDesc': 'Einstellungs- und Favoritenbuttons auf jedem Sound ausblenden',
      'hideCategories': 'Kategorien ausblenden',
      'hidePlayback': 'Wiedergabeleiste ausblenden',
      'volumeControl': 'Lautstärkeregler',
      'displayOptions': 'Anzeigeoptionen',
      'displayOptionsDesc': 'Wähle, was auf dem Soundboard angezeigt wird',
      'hideFavoriteButton': 'Favoriten-Button ausblenden',
      'hideSettingsButton': 'Einstellungs-Button ausblenden',
      'hapticFeedback': 'Vibration',
      'backupRestore': 'Sicherung & Wiederherstellung',
      'backupRestoreDesc': 'Exportiere deine Sounds oder stelle sie aus einer Sicherung wieder her.',
      'exportSounds': 'Sounds exportieren',
      'importSounds': 'Sounds importieren',
      'toolbarButtons': 'Toolbar-Schaltflächen',
      'toolbarButtonsDesc': 'Wähle, welche Schaltflächen in der oberen Leiste erscheinen',
      'darkMode': 'Dunkelmodus',
      'supportTitle': 'Entwickler unterstützen',
      'supportDesc': 'Wenn dir die App gefällt, kauf mir einen Kaffee!',
      'donateButton': 'Einen Kaffee kaufen',
      'noCategoryTitle': 'Keine Kategorie',
      'noCategoryMessage': 'Dieser Sound erscheint nur unter „Alles". Trotzdem hinzufügen?',
      'addAnyway': 'Trotzdem hinzufügen',
      'fadeGlobalDescription': 'Globale Einstellung für alle Sounds',
    },
    'ru': {
      'settings': 'Настройки',
      'addSound': 'Добавить звук',
      'addSoundDesc': 'Добавить свои звуки на саундборд',
      'loop': 'Повтор',
      'shufflePlay': 'Случайное воспроизведение',
      'playbackSpeed': 'Скорость воспроизведения',
      'deleteMode': 'Режим удаления',
      'cancelDeleteMode': 'Отменить режим удаления',
      'searchSounds': 'Поиск звуков...',
      'noSoundPlaying': 'Ничего не воспроизводится',
      'nowPlaying': 'Играет:',
      'soundsCount': 'звуков',
      'noSoundsFound': 'Звуки не найдены',
      'tryChangingSearch': 'Попробуйте изменить поиск или категорию',
      'restoringSound': 'Восстановление звуков...',
      'pleaseWait': 'Пожалуйста, подождите',
      'resetSounds': 'Сбросить звуки',
      'resetSoundsDescription': 'Это удалит все текущие звуки и перезагрузит оригинальные звуки с их категориями.',
      'resetToDefault': 'Сбросить до стандартных звуков',
      'resetConfirmTitle': 'Сбросить звуки',
      'resetConfirmMessage': 'Это удалит все текущие звуки и перезагрузит оригинальные звуки с их категориями.\n\nВы хотите продолжить?',
      'cancel': 'Отмена',
      'reset': 'Сбросить',
      'deleteAll': 'Удалить всё',
      'deleteAllSounds': 'Удалить все звуки',
      'deleteAllConfirmTitle': 'Удалить все звуки',
      'deleteAllConfirmMessage': 'Это навсегда удалит все звуки. Действие нельзя отменить.\n\nХотите продолжить?',
      'manageCategories': 'Управление категориями',
      'manageCategoriesDescription': 'Удалите категории, которые вам больше не нужны. Все звуки с этой категорией её потеряют.',
      'trimSound': 'Обрезать звук',
      'trimReset': 'Сбросить обрезку',
      'trimLoading': 'Загрузка...',
      'editCategory': 'Редактировать категорию',
      'newCategoryName': 'Новое название',
      'deleteCategory': 'Удалить категорию',
      'deleteCategoryConfirm': 'Вы уверены, что хотите удалить "{category}"?\n\nВсе звуки с этой категорией её потеряют.',
      'deleteSoundsAlso': 'Также удалить все звуки с этой категорией',
      'delete': 'Удалить',
      'noCustomCategories': 'Пока нет пользовательских категорий',
      'language': 'Язык',
      'selectLanguage': 'Выберите предпочитаемый язык',
      'soundName': 'Название звука',
      'categories': 'Категории',
      'add': 'Добавить',
      'newCategory': 'Новая категория',
      'enterCategoryName': 'Введите название категории',
      'buttonColor': 'Цвет кнопки',
      'save': 'Сохранить',
      'addNewSound': 'Добавить новый звук',
      'categoryName': 'Название категории',
      'stopRecording': 'Остановить запись',
      'record': 'Записать',
      'play': 'Воспроизвести',
      'stop': 'Остановить',
      'pickFile': 'Выбрать файл',
      'addCategory': 'Добавить категорию',
      'saveSound': 'Сохранить звук',
      'filter': 'Фильтр:',
      'search': 'Поиск:',
      'soundsOnlyInEverything': 'звуков без категории — они будут видны только в Всё',
      'errorDeletingSound': 'Ошибка удаления звука:',
      'errorPlayingSound': 'Ошибка воспроизведения:',
      'fileNotExist': 'Файл не найден в хранилище',
      'speed05': '0.5x Медленно',
      'speed10': '1.0x Нормально',
      'speed20': '2.0x Быстро',
      'privacySettings': 'Настройки конфиденциальности',
      'privacySettingsDesc': 'Управляйте предпочтениями персонализации рекламы',
      'managePrivacy': 'Управление конфиденциальностью',
      'volume': 'Громкость',
      'everything': 'Всё',
      'favorite': 'Избранное',
      'simpleMode': 'Простой режим',
      'simpleModeDesc': 'Скрыть кнопки настроек и избранного на каждом звуке',
      'hideCategories': 'Скрыть категории',
      'hidePlayback': 'Скрыть плеер',
      'volumeControl': 'Регулятор громкости',
      'displayOptions': 'Параметры отображения',
      'displayOptionsDesc': 'Выберите, что отображать на саундборде',
      'hideFavoriteButton': 'Скрыть кнопку избранного',
      'hideSettingsButton': 'Скрыть кнопку настроек',
      'hapticFeedback': 'Вибрация',
      'backupRestore': 'Резервная копия',
      'backupRestoreDesc': 'Экспортируйте звуки или восстановите из резервной копии.',
      'exportSounds': 'Экспорт звуков',
      'importSounds': 'Импорт звуков',
      'toolbarButtons': 'Кнопки панели',
      'toolbarButtonsDesc': 'Выберите, какие кнопки отображаются на верхней панели',
      'darkMode': 'Тёмный режим',
      'supportTitle': 'Поддержать разработчика',
      'supportDesc': 'Если вам нравится приложение, угостите меня кофе!',
      'donateButton': 'Угостить кофе',
      'noCategoryTitle': 'Категория не выбрана',
      'noCategoryMessage': 'Этот звук будет отображаться только в «Всё». Добавить всё равно?',
      'addAnyway': 'Добавить всё равно',
      'fadeGlobalDescription': 'Глобальная настройка для всех звуков',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'sk', 'es', 'fr', 'de', 'ru'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
