import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'addSound': 'Add Sound',
      'addSoundDesc': 'Add custom sounds to your soundboard',
      'loop': 'Loop',
      'shufflePlay': 'Shuffle Play',
      'playbackSpeed': 'Playback Speed',
      'deleteMode': 'Delete mode',
      'cancelDeleteMode': 'Cancel delete mode',
      'searchSounds': 'Search sounds...',
      'noSoundPlaying': 'No sound playing',
      'nowPlaying': 'Now playing:',
      'soundsCount': 'sounds',
      'noSoundsFound': 'No sounds found',
      'tryChangingSearch': 'Try changing your search or category',
      'restoringSound': 'Restoring sounds...',
      'pleaseWait': 'Please wait a moment',
      'resetSounds': 'Reset Sounds',
      'resetSoundsDescription': 'This will delete all current sounds and reload the original sounds with their categories.',
      'resetToDefault': 'Reset to default sounds',
      'resetConfirmTitle': 'Reset sounds',
      'resetConfirmMessage': 'This will delete all current sounds and reload the original sounds with their categories.\n\nDo you want to continue?',
      'cancel': 'Cancel',
      'reset': 'Reset',
      'manageCategories': 'Manage Categories',
      'manageCategoriesDescription': 'Delete categories that you no longer need. All sounds with this category will lose it.',
      'deleteCategory': 'Delete category',
      'deleteCategoryConfirm': 'Are you sure you want to delete "{category}"?\n\nAll sounds with this category will lose it.',
      'delete': 'Delete',
      'noCustomCategories': 'No custom categories yet',
      'language': 'Language',
      'selectLanguage': 'Select your preferred language',
      'soundName': 'Sound name',
      'categories': 'Categories',
      'add': 'Add',
      'newCategory': 'New category',
      'enterCategoryName': 'Enter category name',
      'buttonColor': 'Button color',
      'save': 'Save',
      'addNewSound': 'Add new sound',
      'categoryName': 'Category name',
      'stopRecording': 'Stop recording',
      'record': 'Record',
      'play': 'Play',
      'pickFile': 'Pick file',
      'addCategory': 'Add category',
      'saveSound': 'Save sound',
      'filter': 'Filter:',
      'search': 'Search:',
      'errorDeletingSound': 'Error deleting sound:',
      'errorPlayingSound': 'Error playing sound:',
      'fileNotExist': 'File does not exist in storage',
      'speed05': '0.5x Speed',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Speed',
    },
    'sk': {
      'settings': 'Nastavenia',
      'addSound': 'Pridať zvuk',
      'addSoundDesc': 'Pridať vlastné zvuky do soundboardu',
      'loop': 'Opakovať',
      'shufflePlay': 'Náhodné prehrávanie',
      'playbackSpeed': 'Rýchlosť prehrávania',
      'deleteMode': 'Režim mazania',
      'cancelDeleteMode': 'Zrušiť režim mazania',
      'searchSounds': 'Hľadať zvuky...',
      'noSoundPlaying': 'Žiadny zvuk sa neprehráva',
      'nowPlaying': 'Práve hrá:',
      'soundsCount': 'zvukov',
      'noSoundsFound': 'Nenašli sa žiadne zvuky',
      'tryChangingSearch': 'Skúste zmeniť vyhľadávanie alebo kategóriu',
      'restoringSound': 'Obnovujem zvuky...',
      'pleaseWait': 'Prosím počkajte chvíľu',
      'resetSounds': 'Resetovať zvuky',
      'resetSoundsDescription': 'Toto vymaže všetky aktuálne zvuky a obnoví pôvodné zvuky s ich kategóriami.',
      'resetToDefault': 'Resetovať na predvolené zvuky',
      'resetConfirmTitle': 'Resetovať zvuky',
      'resetConfirmMessage': 'Toto vymaže všetky aktuálne zvuky a obnoví pôvodné zvuky s ich kategóriami.\n\nChcete pokračovať?',
      'cancel': 'Zrušiť',
      'reset': 'Resetovať',
      'manageCategories': 'Spravovať kategórie',
      'manageCategoriesDescription': 'Vymažte kategórie, ktoré už nepotrebujete. Všetky zvuky s touto kategóriou ju stratia.',
      'deleteCategory': 'Vymazať kategóriu',
      'deleteCategoryConfirm': 'Naozaj chcete vymazať "{category}"?\n\nVšetky zvuky s touto kategóriou ju stratia.',
      'delete': 'Vymazať',
      'noCustomCategories': 'Zatiaľ žiadne vlastné kategórie',
      'language': 'Jazyk',
      'selectLanguage': 'Vyberte si preferovaný jazyk',
      'soundName': 'Názov zvuku',
      'categories': 'Kategórie',
      'add': 'Pridať',
      'newCategory': 'Nová kategória',
      'enterCategoryName': 'Zadajte názov kategórie',
      'buttonColor': 'Farba tlačidla',
      'save': 'Uložiť',
      'addNewSound': 'Pridať nový zvuk',
      'categoryName': 'Názov kategórie',
      'stopRecording': 'Zastaviť nahrávanie',
      'record': 'Nahrať',
      'play': 'Prehrať',
      'pickFile': 'Vybrať súbor',
      'addCategory': 'Pridať kategóriu',
      'saveSound': 'Uložiť zvuk',
      'filter': 'Filter:',
      'search': 'Hľadať:',
      'errorDeletingSound': 'Chyba pri mazaní zvuku:',
      'errorPlayingSound': 'Chyba pri prehrávaní zvuku:',
      'fileNotExist': 'Súbor neexistuje v úložisku',
      'speed05': '0.5x Rýchlosť',
      'speed10': '1.0x Normálna',
      'speed20': '2.0x Rýchlosť',
    },
    'es': {
      'settings': 'Configuración',
      'addSound': 'Agregar sonido',
      'addSoundDesc': 'Agregar sonidos personalizados a tu soundboard',
      'loop': 'Repetir',
      'shufflePlay': 'Reproducción aleatoria',
      'playbackSpeed': 'Velocidad de reproducción',
      'deleteMode': 'Modo de eliminación',
      'cancelDeleteMode': 'Cancelar modo de eliminación',
      'searchSounds': 'Buscar sonidos...',
      'noSoundPlaying': 'No hay sonido reproduciéndose',
      'nowPlaying': 'Reproduciendo:',
      'soundsCount': 'sonidos',
      'noSoundsFound': 'No se encontraron sonidos',
      'tryChangingSearch': 'Intenta cambiar tu búsqueda o categoría',
      'restoringSound': 'Restaurando sonidos...',
      'pleaseWait': 'Por favor espera un momento',
      'resetSounds': 'Restablecer sonidos',
      'resetSoundsDescription': 'Esto eliminará todos los sonidos actuales y recargará los sonidos originales con sus categorías.',
      'resetToDefault': 'Restablecer a sonidos predeterminados',
      'resetConfirmTitle': 'Restablecer sonidos',
      'resetConfirmMessage': 'Esto eliminará todos los sonidos actuales y recargará los sonidos originales con sus categorías.\n\n¿Deseas continuar?',
      'cancel': 'Cancelar',
      'reset': 'Restablecer',
      'manageCategories': 'Gestionar categorías',
      'manageCategoriesDescription': 'Elimina las categorías que ya no necesites. Todos los sonidos con esta categoría la perderán.',
      'deleteCategory': 'Eliminar categoría',
      'deleteCategoryConfirm': '¿Estás seguro de que deseas eliminar "{category}"?\n\nTodos los sonidos con esta categoría la perderán.',
      'delete': 'Eliminar',
      'noCustomCategories': 'Aún no hay categorías personalizadas',
      'language': 'Idioma',
      'selectLanguage': 'Selecciona tu idioma preferido',
      'soundName': 'Nombre del sonido',
      'categories': 'Categorías',
      'add': 'Agregar',
      'newCategory': 'Nueva categoría',
      'enterCategoryName': 'Ingresa el nombre de la categoría',
      'buttonColor': 'Color del botón',
      'save': 'Guardar',
      'addNewSound': 'Agregar nuevo sonido',
      'categoryName': 'Nombre de categoría',
      'stopRecording': 'Detener grabación',
      'record': 'Grabar',
      'play': 'Reproducir',
      'pickFile': 'Seleccionar archivo',
      'addCategory': 'Agregar categoría',
      'saveSound': 'Guardar sonido',
      'filter': 'Filtro:',
      'search': 'Buscar:',
      'errorDeletingSound': 'Error al eliminar sonido:',
      'errorPlayingSound': 'Error al reproducir sonido:',
      'fileNotExist': 'El archivo no existe en el almacenamiento',
      'speed05': '0.5x Velocidad',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Velocidad',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'sk', 'es'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
