import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'addSound': 'Add Sound',
      'addSoundDesc': 'Add custom sounds to your soundboard',
      'loop': 'Loop',
      'shufflePlay': 'Shuffle Play',
      'playbackSpeed': 'Playback Speed',
      'deleteMode': 'Delete mode',
      'cancelDeleteMode': 'Cancel delete mode',
      'searchSounds': 'Search sounds...',
      'noSoundPlaying': 'No sound playing',
      'nowPlaying': 'Now playing:',
      'soundsCount': 'sounds',
      'noSoundsFound': 'No sounds found',
      'tryChangingSearch': 'Try changing your search or category',
      'restoringSound': 'Restoring sounds...',
      'pleaseWait': 'Please wait a moment',
      'resetSounds': 'Reset Sounds',
      'resetSoundsDescription': 'This will delete all current sounds and reload the original sounds with their categories.',
      'resetToDefault': 'Reset to default sounds',
      'resetConfirmTitle': 'Reset sounds',
      'resetConfirmMessage': 'This will delete all current sounds and reload the original sounds with their categories.\n\nDo you want to continue?',
      'cancel': 'Cancel',
      'reset': 'Reset',
      'deleteAll': 'Delete All',
      'deleteAllSounds': 'Delete all sounds',
      'deleteAllConfirmTitle': 'Delete all sounds',
      'deleteAllConfirmMessage': 'This will permanently delete all sounds. This cannot be undone.\n\nDo you want to continue?',
      'manageCategories': 'Manage Categories',
      'manageCategoriesDescription': 'Delete categories that you no longer need. All sounds with this category will lose it.',
      'trimSound': 'Trim sound',
      'trimReset': 'Reset trim',
      'trimLoading': 'Loading...',
      'editCategory': 'Edit category',
      'newCategoryName': 'New name',
      'deleteCategory': 'Delete category',
      'deleteCategoryConfirm': 'Are you sure you want to delete "{category}"?\n\nAll sounds with this category will lose it.',
      'deleteSoundsAlso': 'Also delete all sounds with this category',
      'delete': 'Delete',
      'noCustomCategories': 'No custom categories yet',
      'language': 'Language',
      'selectLanguage': 'Select your preferred language',
      'soundName': 'Sound name',
      'categories': 'Categories',
      'add': 'Add',
      'newCategory': 'New category',
      'enterCategoryName': 'Enter category name',
      'buttonColor': 'Button color',
      'save': 'Save',
      'addNewSound': 'Add new sound',
      'categoryName': 'Category name',
      'stopRecording': 'Stop recording',
      'record': 'Record',
      'play': 'Play',
      'stop': 'Stop',
      'pickFile': 'Pick file',
      'addCategory': 'Add category',
      'saveSound': 'Save sound',
      'filter': 'Filter:',
      'search': 'Search:',
      'soundsOnlyInEverything': 'sounds have no category and will only appear in Everything',
      'errorDeletingSound': 'Error deleting sound:',
      'errorPlayingSound': 'Error playing sound:',
      'fileNotExist': 'File does not exist in storage',
      'speed05': '0.5x Speed',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Speed',
      'privacySettings': 'Privacy Settings',
      'privacySettingsDesc': 'Manage your ad personalization preferences',
      'managePrivacy': 'Manage Privacy',
      'volume': 'Volume',
      'everything': 'Everything',
      'favorite': 'Favorite',
      'simpleMode': 'Simple Mode',
      'simpleModeDesc': 'Hide settings and favourite buttons on each sound',
      'hideCategories': 'Hide categories',
      'hidePlayback': 'Hide playback bar',
      'hapticFeedback': 'Vibration',
      'backupRestore': 'Backup & Restore',
      'backupRestoreDesc': 'Export your sounds to a file or restore from a previous backup.',
      'exportSounds': 'Export sounds',
      'importSounds': 'Import sounds',
      'toolbarButtons': 'Toolbar Buttons',
      'toolbarButtonsDesc': 'Choose which buttons appear in the top toolbar',
      'darkMode': 'Dark Mode',
      'supportTitle': 'Support the Developer',
      'supportDesc': 'If you enjoy the app, consider buying me a coffee!',
      'donateButton': 'Buy me a coffee',
      'noCategoryTitle': 'No category selected',
      'noCategoryMessage': 'This sound will only appear in "Everything". Add anyway?',
      'addAnyway': 'Add anyway',
      'volumeControl': 'Volume control',
      'displayOptions': 'Display Options',
      'displayOptionsDesc': 'Choose what to show on the soundboard',
      'hideFavoriteButton': 'Hide favorite button',
      'hideSettingsButton': 'Hide settings button',
      'fadeGlobalDescription': 'Global setting for all sounds',
      'hideVolumeBar': 'Hide Volume Bar',
      'exportSaved': 'Saved: ',
      'exportFailed': 'Export failed: ',
      'importFailed': 'Import failed: ',
    },
    'pt': {
      'settings': 'Configurações',
      'addSound': 'Adicionar som',
      'addSoundDesc': 'Adicionar sons personalizados ao seu soundboard',
      'loop': 'Repetir',
      'shufflePlay': 'Reprodução aleatória',
      'playbackSpeed': 'Velocidade de reprodução',
      'deleteMode': 'Modo exclusão',
      'cancelDeleteMode': 'Cancelar modo exclusão',
      'searchSounds': 'Pesquisar sons...',
      'noSoundPlaying': 'Nenhum som sendo reproduzido',
      'nowPlaying': 'A tocar:',
      'soundsCount': 'sons',
      'noSoundsFound': 'Nenhum som encontrado',
      'tryChangingSearch': 'Tente alterar a pesquisa ou categoria',
      'restoringSound': 'A restaurar sons...',
      'pleaseWait': 'Por favor aguarde um momento',
      'resetSounds': 'Redefinir sons',
      'resetSoundsDescription': 'Isso excluirá todos os sons atuais e recarregará os sons originais com suas categorias.',
      'resetToDefault': 'Redefinir para sons padrão',
      'resetConfirmTitle': 'Redefinir sons',
      'resetConfirmMessage': 'Isso excluirá todos os sons atuais e recarregará os sons originais com suas categorias.\n\nDeseja continuar?',
      'cancel': 'Cancelar',
      'reset': 'Redefinir',
      'deleteAll': 'Excluir tudo',
      'deleteAllSounds': 'Excluir todos os sons',
      'deleteAllConfirmTitle': 'Excluir todos os sons',
      'deleteAllConfirmMessage': 'Isso excluirá permanentemente todos os sons. Esta ação não pode ser desfeita.\n\nDeseja continuar?',
      'manageCategories': 'Gerenciar categorias',
      'manageCategoriesDescription': 'Exclua categorias que não precisar mais. Todos os sons com essa categoria a perderão.',
      'trimSound': 'Aparar som',
      'trimReset': 'Redefinir aparação',
      'trimLoading': 'Carregando...',
      'editCategory': 'Editar categoria',
      'newCategoryName': 'Novo nome',
      'deleteCategory': 'Excluir categoria',
      'deleteCategoryConfirm': 'Tem certeza que deseja excluir "{category}"?\n\nTodos os sons com essa categoria a perderão.',
      'deleteSoundsAlso': 'Também excluir todos os sons desta categoria',
      'delete': 'Excluir',
      'noCustomCategories': 'Nenhuma categoria personalizada ainda',
      'language': 'Idioma',
      'selectLanguage': 'Selecione seu idioma preferido',
      'soundName': 'Nome do som',
      'categories': 'Categorias',
      'add': 'Adicionar',
      'newCategory': 'Nova categoria',
      'enterCategoryName': 'Digite o nome da categoria',
      'buttonColor': 'Cor do botão',
      'save': 'Salvar',
      'addNewSound': 'Adicionar novo som',
      'categoryName': 'Nome da categoria',
      'stopRecording': 'Parar gravação',
      'record': 'Gravar',
      'play': 'Reproduzir',
      'stop': 'Parar',
      'pickFile': 'Escolher arquivo',
      'addCategory': 'Adicionar categoria',
      'saveSound': 'Salvar som',
      'filter': 'Filtro:',
      'search': 'Pesquisar:',
      'soundsOnlyInEverything': 'sons não têm categoria e aparecerão apenas em Tudo',
      'errorDeletingSound': 'Erro ao excluir som:',
      'errorPlayingSound': 'Erro ao reproduzir som:',
      'fileNotExist': 'Arquivo não encontrado no armazenamento',
      'speed05': '0.5x Lento',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Rápido',
      'privacySettings': 'Configurações de privacidade',
      'privacySettingsDesc': 'Gerencie suas preferências de personalização de anúncios',
      'managePrivacy': 'Gerenciar privacidade',
      'volume': 'Volume',
      'everything': 'Tudo',
      'favorite': 'Favorito',
      'simpleMode': 'Modo simples',
      'simpleModeDesc': 'Ocultar botões de configurações e favoritos em cada som',
      'hideCategories': 'Ocultar categorias',
      'hidePlayback': 'Ocultar reprodutor',
      'hapticFeedback': 'Vibração',
      'backupRestore': 'Backup e restauração',
      'backupRestoreDesc': 'Exporte seus sons ou restaure de um backup anterior.',
      'exportSounds': 'Exportar sons',
      'importSounds': 'Importar sons',
      'toolbarButtons': 'Botões da barra',
      'toolbarButtonsDesc': 'Escolha quais botões aparecem na barra superior',
      'darkMode': 'Modo escuro',
      'supportTitle': 'Apoiar o desenvolvedor',
      'supportDesc': 'Se você gosta do app, considere me pagar um café!',
      'donateButton': 'Me pagar um café',
      'noCategoryTitle': 'Sem categoria',
      'noCategoryMessage': 'Este som aparecerá apenas em "Tudo". Adicionar mesmo assim?',
      'addAnyway': 'Adicionar mesmo assim',
      'volumeControl': 'Controle de volume',
      'displayOptions': 'Opções de exibição',
      'displayOptionsDesc': 'Escolha o que mostrar no soundboard',
      'hideFavoriteButton': 'Ocultar botão de favoritos',
      'hideSettingsButton': 'Ocultar botão de configurações',
      'fadeGlobalDescription': 'Configuração global para todos os sons',
      'hideVolumeBar': 'Ocultar barra de volume',
      'exportSaved': 'Salvo: ',
      'exportFailed': 'Falha na exportação: ',
      'importFailed': 'Falha na importação: ',
    },
    'es': {
      'settings': 'Configuración',
      'addSound': 'Agregar sonido',
      'addSoundDesc': 'Agregar sonidos personalizados a tu soundboard',
      'loop': 'Repetir',
      'shufflePlay': 'Reproducción aleatoria',
      'playbackSpeed': 'Velocidad de reproducción',
      'deleteMode': 'Modo de eliminación',
      'cancelDeleteMode': 'Cancelar modo de eliminación',
      'searchSounds': 'Buscar sonidos...',
      'noSoundPlaying': 'No hay sonido reproduciéndose',
      'nowPlaying': 'Reproduciendo:',
      'soundsCount': 'sonidos',
      'noSoundsFound': 'No se encontraron sonidos',
      'tryChangingSearch': 'Intenta cambiar tu búsqueda o categoría',
      'restoringSound': 'Restaurando sonidos...',
      'pleaseWait': 'Por favor espera un momento',
      'resetSounds': 'Restablecer sonidos',
      'resetSoundsDescription': 'Esto eliminará todos los sonidos actuales y recargará los sonidos originales con sus categorías.',
      'resetToDefault': 'Restablecer a sonidos predeterminados',
      'resetConfirmTitle': 'Restablecer sonidos',
      'resetConfirmMessage': 'Esto eliminará todos los sonidos actuales y recargará los sonidos originales con sus categorías.\n\n¿Deseas continuar?',
      'cancel': 'Cancelar',
      'reset': 'Restablecer',
      'deleteAll': 'Eliminar todo',
      'deleteAllSounds': 'Eliminar todos los sonidos',
      'deleteAllConfirmTitle': 'Eliminar todos los sonidos',
      'deleteAllConfirmMessage': 'Esto eliminará permanentemente todos los sonidos. No se puede deshacer.\n\n¿Desea continuar?',
      'manageCategories': 'Gestionar categorías',
      'manageCategoriesDescription': 'Elimina las categorías que ya no necesites. Todos los sonidos con esta categoría la perderán.',
      'trimSound': 'Recortar sonido',
      'trimReset': 'Restablecer recorte',
      'trimLoading': 'Cargando...',
      'editCategory': 'Editar categoría',
      'newCategoryName': 'Nuevo nombre',
      'deleteCategory': 'Eliminar categoría',
      'deleteCategoryConfirm': '¿Estás seguro de que deseas eliminar "{category}"?\n\nTodos los sonidos con esta categoría la perderán.',
      'deleteSoundsAlso': 'También eliminar todos los sonidos con esta categoría',
      'delete': 'Eliminar',
      'noCustomCategories': 'Aún no hay categorías personalizadas',
      'language': 'Idioma',
      'selectLanguage': 'Selecciona tu idioma preferido',
      'soundName': 'Nombre del sonido',
      'categories': 'Categorías',
      'add': 'Agregar',
      'newCategory': 'Nueva categoría',
      'enterCategoryName': 'Ingresa el nombre de la categoría',
      'buttonColor': 'Color del botón',
      'save': 'Guardar',
      'addNewSound': 'Agregar nuevo sonido',
      'categoryName': 'Nombre de categoría',
      'stopRecording': 'Detener grabación',
      'record': 'Grabar',
      'play': 'Reproducir',
      'stop': 'Detener',
      'pickFile': 'Seleccionar archivo',
      'addCategory': 'Agregar categoría',
      'saveSound': 'Guardar sonido',
      'filter': 'Filtro:',
      'search': 'Buscar:',
      'soundsOnlyInEverything': 'sonidos no tienen categoría y solo aparecerán en Todo',
      'errorDeletingSound': 'Error al eliminar sonido:',
      'errorPlayingSound': 'Error al reproducir sonido:',
      'fileNotExist': 'El archivo no existe en el almacenamiento',
      'speed05': '0.5x Velocidad',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Velocidad',
      'privacySettings': 'Configuración de privacidad',
      'privacySettingsDesc': 'Administra tus preferencias de personalización de anuncios',
      'managePrivacy': 'Gestionar privacidad',
      'volume': 'Volumen',
      'everything': 'Todo',
      'favorite': 'Favorito',
      'simpleMode': 'Modo simple',
      'simpleModeDesc': 'Ocultar los botones de ajustes y favoritos en cada sonido',
      'hideCategories': 'Ocultar categorías',
      'hidePlayback': 'Ocultar reproductor',
      'hapticFeedback': 'Vibración',
      'backupRestore': 'Copia de seguridad',
      'backupRestoreDesc': 'Exporta tus sonidos o restaura desde una copia de seguridad.',
      'exportSounds': 'Exportar sonidos',
      'importSounds': 'Importar sonidos',
      'toolbarButtons': 'Botones de barra',
      'toolbarButtonsDesc': 'Elige qué botones aparecen en la barra superior',
      'darkMode': 'Modo oscuro',
      'supportTitle': 'Apoya al desarrollador',
      'supportDesc': '¡Si disfrutas la app, considera invitarme un café!',
      'donateButton': 'Invítame un café',
      'noCategoryTitle': 'Sin categoría',
      'noCategoryMessage': 'Este sonido solo aparecerá en "Todo". ¿Añadir de todas formas?',
      'addAnyway': 'Añadir de todas formas',
      'volumeControl': 'Control de volumen',
      'displayOptions': 'Opciones de pantalla',
      'displayOptionsDesc': 'Elige qué mostrar en el soundboard',
      'hideFavoriteButton': 'Ocultar botón de favoritos',
      'hideSettingsButton': 'Ocultar botón de ajustes',
      'fadeGlobalDescription': 'Configuración global para todos los sonidos',
      'hideVolumeBar': 'Ocultar barra de volumen',
      'exportSaved': 'Guardado: ',
      'exportFailed': 'Error al exportar: ',
      'importFailed': 'Error al importar: ',
    },
    'fr': {
      'settings': 'Paramètres',
      'addSound': 'Ajouter un son',
      'addSoundDesc': 'Ajouter des sons personnalisés à votre soundboard',
      'loop': 'Répéter',
      'shufflePlay': 'Lecture aléatoire',
      'playbackSpeed': 'Vitesse de lecture',
      'deleteMode': 'Mode suppression',
      'cancelDeleteMode': 'Annuler le mode suppression',
      'searchSounds': 'Rechercher des sons...',
      'noSoundPlaying': 'Aucun son en cours',
      'nowPlaying': 'En cours :',
      'soundsCount': 'sons',
      'noSoundsFound': 'Aucun son trouvé',
      'tryChangingSearch': 'Modifiez votre recherche ou catégorie',
      'restoringSound': 'Restauration des sons...',
      'pleaseWait': 'Patientez un instant',
      'resetSounds': 'Réinitialiser les sons',
      'resetSoundsDescription': 'Cela supprimera tous les sons actuels et rechargera les sons originaux avec leurs catégories.',
      'resetToDefault': 'Réinitialiser aux sons par défaut',
      'resetConfirmTitle': 'Réinitialiser les sons',
      'resetConfirmMessage': 'Cela supprimera tous les sons actuels et rechargera les sons originaux avec leurs catégories.\n\nVoulez-vous continuer ?',
      'cancel': 'Annuler',
      'reset': 'Réinitialiser',
      'deleteAll': 'Tout supprimer',
      'deleteAllSounds': 'Supprimer tous les sons',
      'deleteAllConfirmTitle': 'Supprimer tous les sons',
      'deleteAllConfirmMessage': 'Cela supprimera définitivement tous les sons. Cette action est irréversible.\n\nVoulez-vous continuer?',
      'manageCategories': 'Gérer les catégories',
      'manageCategoriesDescription': 'Supprimez les catégories dont vous n\'avez plus besoin. Tous les sons de cette catégorie la perdront.',
      'trimSound': 'Rogner le son',
      'trimReset': 'Réinitialiser le rognage',
      'trimLoading': 'Chargement...',
      'editCategory': 'Modifier la catégorie',
      'newCategoryName': 'Nouveau nom',
      'deleteCategory': 'Supprimer la catégorie',
      'deleteCategoryConfirm': 'Êtes-vous sûr de vouloir supprimer "{category}" ?\n\nTous les sons de cette catégorie la perdront.',
      'deleteSoundsAlso': 'Supprimer aussi tous les sons de cette catégorie',
      'delete': 'Supprimer',
      'noCustomCategories': 'Aucune catégorie personnalisée pour l\'instant',
      'language': 'Langue',
      'selectLanguage': 'Sélectionnez votre langue préférée',
      'soundName': 'Nom du son',
      'categories': 'Catégories',
      'add': 'Ajouter',
      'newCategory': 'Nouvelle catégorie',
      'enterCategoryName': 'Entrez le nom de la catégorie',
      'buttonColor': 'Couleur du bouton',
      'save': 'Enregistrer',
      'addNewSound': 'Ajouter un nouveau son',
      'categoryName': 'Nom de la catégorie',
      'stopRecording': 'Arrêter l\'enregistrement',
      'record': 'Enregistrer',
      'play': 'Lire',
      'stop': 'Arrêter',
      'pickFile': 'Choisir un fichier',
      'addCategory': 'Ajouter une catégorie',
      'saveSound': 'Enregistrer le son',
      'filter': 'Filtrer',
      'search': 'Rechercher',
      'soundsOnlyInEverything': 'sons n\'ont pas de catégorie et n\'apparaîtront que dans Tout',
      'errorDeletingSound': 'Erreur lors de la suppression du son :',
      'errorPlayingSound': 'Erreur lors de la lecture du son :',
      'fileNotExist': 'Le fichier n\'existe pas dans le stockage',
      'speed05': '0.5x Vitesse',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Vitesse',
      'privacySettings': 'Paramètres de confidentialité',
      'privacySettingsDesc': 'Gérez vos préférences de personnalisation des publicités',
      'managePrivacy': 'Gérer la confidentialité',
      'volume': 'Volume',
      'everything': 'Tous',
      'favorite': 'Favori',
      'simpleMode': 'Mode simple',
      'simpleModeDesc': 'Masquer les boutons de réglages et favoris sur chaque son',
      'hideCategories': 'Masquer les catégories',
      'hidePlayback': 'Masquer le lecteur',
      'hapticFeedback': 'Vibration',
      'backupRestore': 'Sauvegarde et restauration',
      'backupRestoreDesc': 'Exportez vos sons ou restaurez depuis une sauvegarde.',
      'exportSounds': 'Exporter les sons',
      'importSounds': 'Importer les sons',
      'toolbarButtons': 'Boutons de barre',
      'toolbarButtonsDesc': 'Choisissez quels boutons apparaissent dans la barre supérieure',
      'darkMode': 'Mode sombre',
      'supportTitle': 'Soutenir le développeur',
      'supportDesc': 'Si vous aimez l\'app, offrez-moi un café !',
      'donateButton': 'Offrir un café',
      'noCategoryTitle': 'Aucune catégorie',
      'noCategoryMessage': 'Ce son apparaîtra uniquement dans « Tous ». Ajouter quand même ?',
      'addAnyway': 'Ajouter quand même',
      'volumeControl': 'Contrôle du volume',
      'displayOptions': 'Options d\'affichage',
      'displayOptionsDesc': 'Choisissez ce qui s\'affiche sur le soundboard',
      'hideFavoriteButton': 'Masquer le bouton favori',
      'hideSettingsButton': 'Masquer le bouton réglages',
      'fadeGlobalDescription': 'Paramètre global pour tous les sons',
      'hideVolumeBar': 'Masquer le volume',
      'exportSaved': 'Enregistré : ',
      'exportFailed': 'Échec de l\'export : ',
      'importFailed': 'Échec de l\'import : ',
    },
    'de': {
      'settings': 'Einstellungen',
      'addSound': 'Sound hinzufügen',
      'addSoundDesc': 'Eigene Sounds zum Soundboard hinzufügen',
      'loop': 'Wiederholen',
      'shufflePlay': 'Zufallswiedergabe',
      'playbackSpeed': 'Wiedergabegeschwindigkeit',
      'deleteMode': 'Löschmodus',
      'cancelDeleteMode': 'Löschmodus beenden',
      'searchSounds': 'Sounds suchen...',
      'noSoundPlaying': 'Kein Sound wird abgespielt',
      'nowPlaying': 'Läuft:',
      'soundsCount': 'Sounds',
      'noSoundsFound': 'Keine Sounds gefunden',
      'tryChangingSearch': 'Versuche, deine Suche oder Kategorie zu ändern',
      'restoringSound': 'Sounds werden wiederhergestellt...',
      'pleaseWait': 'Bitte einen Moment warten',
      'resetSounds': 'Sounds zurücksetzen',
      'resetSoundsDescription': 'Dies löscht alle aktuellen Sounds und lädt die Original-Sounds mit ihren Kategorien neu.',
      'resetToDefault': 'Auf Standard-Sounds zurücksetzen',
      'resetConfirmTitle': 'Sounds zurücksetzen',
      'resetConfirmMessage': 'Dies löscht alle aktuellen Sounds und lädt die Original-Sounds mit ihren Kategorien neu.\n\nMöchtest du fortfahren?',
      'cancel': 'Abbrechen',
      'reset': 'Zurücksetzen',
      'deleteAll': 'Alle löschen',
      'deleteAllSounds': 'Alle Sounds löschen',
      'deleteAllConfirmTitle': 'Alle Sounds löschen',
      'deleteAllConfirmMessage': 'Dies löscht alle Sounds dauerhaft. Dies kann nicht rückgängig gemacht werden.\n\nMöchten Sie fortfahren?',
      'manageCategories': 'Kategorien verwalten',
      'manageCategoriesDescription': 'Lösche Kategorien, die du nicht mehr benötigst. Alle Sounds mit dieser Kategorie verlieren sie.',
      'trimSound': 'Sound trimmen',
      'trimReset': 'Trim zurücksetzen',
      'trimLoading': 'Lädt...',
      'editCategory': 'Kategorie bearbeiten',
      'newCategoryName': 'Neuer Name',
      'deleteCategory': 'Kategorie löschen',
      'deleteCategoryConfirm': 'Bist du sicher, dass du "{category}" löschen möchtest?\n\nAlle Sounds mit dieser Kategorie verlieren sie.',
      'deleteSoundsAlso': 'Auch alle Sounds mit dieser Kategorie löschen',
      'delete': 'Löschen',
      'noCustomCategories': 'Noch keine eigenen Kategorien',
      'language': 'Sprache',
      'selectLanguage': 'Wähle deine bevorzugte Sprache',
      'soundName': 'Soundname',
      'categories': 'Kategorien',
      'add': 'Hinzufügen',
      'newCategory': 'Neue Kategorie',
      'enterCategoryName': 'Kategorienamen eingeben',
      'buttonColor': 'Buttonfarbe',
      'save': 'Speichern',
      'addNewSound': 'Neuen Sound hinzufügen',
      'categoryName': 'Kategoriename',
      'stopRecording': 'Aufnahme stoppen',
      'record': 'Aufnehmen',
      'play': 'Abspielen',
      'stop': 'Stoppen',
      'pickFile': 'Datei auswählen',
      'addCategory': 'Kategorie hinzufügen',
      'saveSound': 'Sound speichern',
      'filter': 'Filter:',
      'search': 'Suchen:',
      'soundsOnlyInEverything': 'Sounds haben keine Kategorie und erscheinen nur in Alles',
      'errorDeletingSound': 'Fehler beim Löschen:',
      'errorPlayingSound': 'Fehler beim Abspielen:',
      'fileNotExist': 'Datei nicht im Speicher gefunden',
      'speed05': '0.5x Langsam',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Schnell',
      'privacySettings': 'Datenschutzeinstellungen',
      'privacySettingsDesc': 'Präferenzen für personalisierte Werbung verwalten',
      'managePrivacy': 'Datenschutz verwalten',
      'volume': 'Lautstärke',
      'everything': 'Alles',
      'favorite': 'Favorit',
      'simpleMode': 'Einfacher Modus',
      'simpleModeDesc': 'Einstellungs- und Favoritenbuttons auf jedem Sound ausblenden',
      'hideCategories': 'Kategorien ausblenden',
      'hidePlayback': 'Wiedergabeleiste ausblenden',
      'hapticFeedback': 'Vibration',
      'backupRestore': 'Sicherung & Wiederherstellung',
      'backupRestoreDesc': 'Exportiere deine Sounds oder stelle sie aus einer Sicherung wieder her.',
      'exportSounds': 'Sounds exportieren',
      'importSounds': 'Sounds importieren',
      'toolbarButtons': 'Toolbar-Schaltflächen',
      'toolbarButtonsDesc': 'Wähle, welche Schaltflächen in der oberen Leiste erscheinen',
      'darkMode': 'Dunkelmodus',
      'supportTitle': 'Entwickler unterstützen',
      'supportDesc': 'Wenn dir die App gefällt, kauf mir einen Kaffee!',
      'donateButton': 'Einen Kaffee kaufen',
      'noCategoryTitle': 'Keine Kategorie',
      'noCategoryMessage': 'Dieser Sound erscheint nur unter „Alles". Trotzdem hinzufügen?',
      'addAnyway': 'Trotzdem hinzufügen',
      'volumeControl': 'Lautstärkeregler',
      'displayOptions': 'Anzeigeoptionen',
      'displayOptionsDesc': 'Wähle, was auf dem Soundboard angezeigt wird',
      'hideFavoriteButton': 'Favoriten-Button ausblenden',
      'hideSettingsButton': 'Einstellungs-Button ausblenden',
      'fadeGlobalDescription': 'Globale Einstellung für alle Sounds',
      'hideVolumeBar': 'Lautstärkeleiste ausblenden',
      'exportSaved': 'Gespeichert: ',
      'exportFailed': 'Export fehlgeschlagen: ',
      'importFailed': 'Import fehlgeschlagen: ',
    },
    'it': {
      'settings': 'Impostazioni',
      'addSound': 'Aggiungi suono',
      'addSoundDesc': 'Aggiungi suoni personalizzati alla tua soundboard',
      'loop': 'Ripeti',
      'shufflePlay': 'Riproduzione casuale',
      'playbackSpeed': 'Velocità di riproduzione',
      'deleteMode': 'Modalità eliminazione',
      'cancelDeleteMode': 'Annulla modalità eliminazione',
      'searchSounds': 'Cerca suoni...',
      'noSoundPlaying': 'Nessun suono in riproduzione',
      'nowPlaying': 'In riproduzione:',
      'soundsCount': 'suoni',
      'noSoundsFound': 'Nessun suono trovato',
      'tryChangingSearch': 'Prova a cambiare la ricerca o la categoria',
      'restoringSound': 'Ripristino suoni...',
      'pleaseWait': 'Attendere un momento',
      'resetSounds': 'Ripristina suoni',
      'resetSoundsDescription': 'Questo eliminerà tutti i suoni attuali e ricaricherà i suoni originali con le loro categorie.',
      'resetToDefault': 'Ripristina suoni predefiniti',
      'resetConfirmTitle': 'Ripristina suoni',
      'resetConfirmMessage': 'Questo eliminerà tutti i suoni attuali e ricaricherà i suoni originali con le loro categorie.\n\nVuoi continuare?',
      'cancel': 'Annulla',
      'reset': 'Ripristina',
      'deleteAll': 'Elimina tutto',
      'deleteAllSounds': 'Elimina tutti i suoni',
      'deleteAllConfirmTitle': 'Elimina tutti i suoni',
      'deleteAllConfirmMessage': 'Questo eliminerà definitivamente tutti i suoni. L\'operazione non può essere annullata.\n\nVuoi continuare?',
      'manageCategories': 'Gestisci categorie',
      'manageCategoriesDescription': 'Elimina le categorie che non ti servono più. Tutti i suoni con questa categoria la perderanno.',
      'trimSound': 'Taglia suono',
      'trimReset': 'Ripristina taglio',
      'trimLoading': 'Caricamento...',
      'editCategory': 'Modifica categoria',
      'newCategoryName': 'Nuovo nome',
      'deleteCategory': 'Elimina categoria',
      'deleteCategoryConfirm': 'Sei sicuro di voler eliminare "{category}"?\n\nTutti i suoni con questa categoria la perderanno.',
      'deleteSoundsAlso': 'Elimina anche tutti i suoni con questa categoria',
      'delete': 'Elimina',
      'noCustomCategories': 'Nessuna categoria personalizzata ancora',
      'language': 'Lingua',
      'selectLanguage': 'Seleziona la tua lingua preferita',
      'soundName': 'Nome del suono',
      'categories': 'Categorie',
      'add': 'Aggiungi',
      'newCategory': 'Nuova categoria',
      'enterCategoryName': 'Inserisci il nome della categoria',
      'buttonColor': 'Colore del pulsante',
      'save': 'Salva',
      'addNewSound': 'Aggiungi nuovo suono',
      'categoryName': 'Nome categoria',
      'stopRecording': 'Interrompi registrazione',
      'record': 'Registra',
      'play': 'Riproduci',
      'stop': 'Ferma',
      'pickFile': 'Scegli file',
      'addCategory': 'Aggiungi categoria',
      'saveSound': 'Salva suono',
      'filter': 'Filtro:',
      'search': 'Cerca:',
      'soundsOnlyInEverything': 'suoni non hanno categoria e appariranno solo in Tutto',
      'errorDeletingSound': 'Errore eliminazione suono:',
      'errorPlayingSound': 'Errore riproduzione suono:',
      'fileNotExist': 'File non trovato nell\'archivio',
      'speed05': '0.5x Lento',
      'speed10': '1.0x Normale',
      'speed20': '2.0x Veloce',
      'privacySettings': 'Impostazioni privacy',
      'privacySettingsDesc': 'Gestisci le tue preferenze di personalizzazione degli annunci',
      'managePrivacy': 'Gestisci privacy',
      'volume': 'Volume',
      'everything': 'Tutto',
      'favorite': 'Preferito',
      'simpleMode': 'Modalità semplice',
      'simpleModeDesc': 'Nascondi i pulsanti impostazioni e preferiti su ogni suono',
      'hideCategories': 'Nascondi categorie',
      'hidePlayback': 'Nascondi lettore',
      'hapticFeedback': 'Vibrazione',
      'backupRestore': 'Backup e ripristino',
      'backupRestoreDesc': 'Esporta i tuoi suoni o ripristina da un backup precedente.',
      'exportSounds': 'Esporta suoni',
      'importSounds': 'Importa suoni',
      'toolbarButtons': 'Pulsanti barra',
      'toolbarButtonsDesc': 'Scegli quali pulsanti appaiono nella barra superiore',
      'darkMode': 'Modalità scura',
      'supportTitle': 'Supporta lo sviluppatore',
      'supportDesc': 'Se ti piace l\'app, considera di offrirmi un caffè!',
      'donateButton': 'Offrimi un caffè',
      'noCategoryTitle': 'Nessuna categoria',
      'noCategoryMessage': 'Questo suono apparirà solo in "Tutto". Aggiungere comunque?',
      'addAnyway': 'Aggiungi comunque',
      'volumeControl': 'Controllo volume',
      'displayOptions': 'Opzioni display',
      'displayOptionsDesc': 'Scegli cosa mostrare sulla soundboard',
      'hideFavoriteButton': 'Nascondi pulsante preferiti',
      'hideSettingsButton': 'Nascondi pulsante impostazioni',
      'fadeGlobalDescription': 'Impostazione globale per tutti i suoni',
      'hideVolumeBar': 'Nascondi barra volume',
      'exportSaved': 'Salvato: ',
      'exportFailed': 'Esportazione fallita: ',
      'importFailed': 'Importazione fallita: ',
    },
    'id': {
      'settings': 'Pengaturan',
      'addSound': 'Tambah suara',
      'addSoundDesc': 'Tambahkan suara kustom ke soundboard Anda',
      'loop': 'Ulangi',
      'shufflePlay': 'Putar acak',
      'playbackSpeed': 'Kecepatan putar',
      'deleteMode': 'Mode hapus',
      'cancelDeleteMode': 'Batal mode hapus',
      'searchSounds': 'Cari suara...',
      'noSoundPlaying': 'Tidak ada suara yang diputar',
      'nowPlaying': 'Sedang diputar:',
      'soundsCount': 'suara',
      'noSoundsFound': 'Tidak ada suara ditemukan',
      'tryChangingSearch': 'Coba ubah pencarian atau kategori Anda',
      'restoringSound': 'Memulihkan suara...',
      'pleaseWait': 'Harap tunggu sebentar',
      'resetSounds': 'Reset suara',
      'resetSoundsDescription': 'Ini akan menghapus semua suara saat ini dan memuat ulang suara asli dengan kategorinya.',
      'resetToDefault': 'Reset ke suara default',
      'resetConfirmTitle': 'Reset suara',
      'resetConfirmMessage': 'Ini akan menghapus semua suara saat ini dan memuat ulang suara asli dengan kategorinya.\n\nApakah Anda ingin melanjutkan?',
      'cancel': 'Batal',
      'reset': 'Reset',
      'deleteAll': 'Hapus semua',
      'deleteAllSounds': 'Hapus semua suara',
      'deleteAllConfirmTitle': 'Hapus semua suara',
      'deleteAllConfirmMessage': 'Ini akan menghapus semua suara secara permanen. Tindakan ini tidak dapat dibatalkan.\n\nApakah Anda ingin melanjutkan?',
      'manageCategories': 'Kelola kategori',
      'manageCategoriesDescription': 'Hapus kategori yang tidak lagi Anda butuhkan. Semua suara dengan kategori ini akan kehilangannya.',
      'trimSound': 'Potong suara',
      'trimReset': 'Reset potongan',
      'trimLoading': 'Memuat...',
      'editCategory': 'Edit kategori',
      'newCategoryName': 'Nama baru',
      'deleteCategory': 'Hapus kategori',
      'deleteCategoryConfirm': 'Apakah Anda yakin ingin menghapus "{category}"?\n\nSemua suara dengan kategori ini akan kehilangannya.',
      'deleteSoundsAlso': 'Juga hapus semua suara dengan kategori ini',
      'delete': 'Hapus',
      'noCustomCategories': 'Belum ada kategori kustom',
      'language': 'Bahasa',
      'selectLanguage': 'Pilih bahasa yang Anda inginkan',
      'soundName': 'Nama suara',
      'categories': 'Kategori',
      'add': 'Tambah',
      'newCategory': 'Kategori baru',
      'enterCategoryName': 'Masukkan nama kategori',
      'buttonColor': 'Warna tombol',
      'save': 'Simpan',
      'addNewSound': 'Tambah suara baru',
      'categoryName': 'Nama kategori',
      'stopRecording': 'Hentikan rekaman',
      'record': 'Rekam',
      'play': 'Putar',
      'stop': 'Hentikan',
      'pickFile': 'Pilih file',
      'addCategory': 'Tambah kategori',
      'saveSound': 'Simpan suara',
      'filter': 'Filter:',
      'search': 'Cari:',
      'soundsOnlyInEverything': 'suara tidak memiliki kategori dan hanya akan muncul di Semua',
      'errorDeletingSound': 'Kesalahan menghapus suara:',
      'errorPlayingSound': 'Kesalahan memutar suara:',
      'fileNotExist': 'File tidak ditemukan di penyimpanan',
      'speed05': '0.5x Lambat',
      'speed10': '1.0x Normal',
      'speed20': '2.0x Cepat',
      'privacySettings': 'Pengaturan privasi',
      'privacySettingsDesc': 'Kelola preferensi personalisasi iklan Anda',
      'managePrivacy': 'Kelola privasi',
      'volume': 'Volume',
      'everything': 'Semua',
      'favorite': 'Favorit',
      'simpleMode': 'Mode sederhana',
      'simpleModeDesc': 'Sembunyikan tombol pengaturan dan favorit pada setiap suara',
      'hideCategories': 'Sembunyikan kategori',
      'hidePlayback': 'Sembunyikan pemutar',
      'hapticFeedback': 'Getar',
      'backupRestore': 'Cadangan & Pemulihan',
      'backupRestoreDesc': 'Ekspor suara Anda ke file atau pulihkan dari cadangan sebelumnya.',
      'exportSounds': 'Ekspor suara',
      'importSounds': 'Impor suara',
      'toolbarButtons': 'Tombol toolbar',
      'toolbarButtonsDesc': 'Pilih tombol mana yang muncul di bilah atas',
      'darkMode': 'Mode gelap',
      'supportTitle': 'Dukung pengembang',
      'supportDesc': 'Jika Anda menikmati aplikasinya, pertimbangkan untuk mentraktir saya kopi!',
      'donateButton': 'Traktir saya kopi',
      'noCategoryTitle': 'Tidak ada kategori',
      'noCategoryMessage': 'Suara ini hanya akan muncul di "Semua". Tetap tambahkan?',
      'addAnyway': 'Tetap tambahkan',
      'volumeControl': 'Kontrol volume',
      'displayOptions': 'Opsi tampilan',
      'displayOptionsDesc': 'Pilih apa yang ditampilkan di soundboard',
      'hideFavoriteButton': 'Sembunyikan tombol favorit',
      'hideSettingsButton': 'Sembunyikan tombol pengaturan',
      'fadeGlobalDescription': 'Pengaturan global untuk semua suara',
      'hideVolumeBar': 'Sembunyikan bilah volume',
      'exportSaved': 'Tersimpan: ',
      'exportFailed': 'Ekspor gagal: ',
      'importFailed': 'Impor gagal: ',
    },
    'ru': {
      'settings': 'Настройки',
      'addSound': 'Добавить звук',
      'addSoundDesc': 'Добавить свои звуки на саундборд',
      'loop': 'Повтор',
      'shufflePlay': 'Случайное воспроизведение',
      'playbackSpeed': 'Скорость воспроизведения',
      'deleteMode': 'Режим удаления',
      'cancelDeleteMode': 'Отменить режим удаления',
      'searchSounds': 'Поиск звуков...',
      'noSoundPlaying': 'Ничего не воспроизводится',
      'nowPlaying': 'Играет:',
      'soundsCount': 'звуков',
      'noSoundsFound': 'Звуки не найдены',
      'tryChangingSearch': 'Попробуйте изменить поиск или категорию',
      'restoringSound': 'Восстановление звуков...',
      'pleaseWait': 'Пожалуйста, подождите',
      'resetSounds': 'Сбросить звуки',
      'resetSoundsDescription': 'Это удалит все текущие звуки и перезагрузит оригинальные звуки с их категориями.',
      'resetToDefault': 'Сбросить до стандартных звуков',
      'resetConfirmTitle': 'Сбросить звуки',
      'resetConfirmMessage': 'Это удалит все текущие звуки и перезагрузит оригинальные звуки с их категориями.\n\nВы хотите продолжить?',
      'cancel': 'Отмена',
      'reset': 'Сбросить',
      'deleteAll': 'Удалить всё',
      'deleteAllSounds': 'Удалить все звуки',
      'deleteAllConfirmTitle': 'Удалить все звуки',
      'deleteAllConfirmMessage': 'Это навсегда удалит все звуки. Действие нельзя отменить.\n\nХотите продолжить?',
      'manageCategories': 'Управление категориями',
      'manageCategoriesDescription': 'Удалите категории, которые вам больше не нужны. Все звуки с этой категорией её потеряют.',
      'trimSound': 'Обрезать звук',
      'trimReset': 'Сбросить обрезку',
      'trimLoading': 'Загрузка...',
      'editCategory': 'Редактировать категорию',
      'newCategoryName': 'Новое название',
      'deleteCategory': 'Удалить категорию',
      'deleteCategoryConfirm': 'Вы уверены, что хотите удалить "{category}"?\n\nВсе звуки с этой категорией её потеряют.',
      'deleteSoundsAlso': 'Также удалить все звуки с этой категорией',
      'delete': 'Удалить',
      'noCustomCategories': 'Пока нет пользовательских категорий',
      'language': 'Язык',
      'selectLanguage': 'Выберите предпочитаемый язык',
      'soundName': 'Название звука',
      'categories': 'Категории',
      'add': 'Добавить',
      'newCategory': 'Новая категория',
      'enterCategoryName': 'Введите название категории',
      'buttonColor': 'Цвет кнопки',
      'save': 'Сохранить',
      'addNewSound': 'Добавить новый звук',
      'categoryName': 'Название категории',
      'stopRecording': 'Остановить запись',
      'record': 'Записать',
      'play': 'Воспроизвести',
      'stop': 'Остановить',
      'pickFile': 'Выбрать файл',
      'addCategory': 'Добавить категорию',
      'saveSound': 'Сохранить звук',
      'filter': 'Фильтр:',
      'search': 'Поиск:',
      'soundsOnlyInEverything': 'звуков без категории — они будут видны только в Всё',
      'errorDeletingSound': 'Ошибка удаления звука:',
      'errorPlayingSound': 'Ошибка воспроизведения:',
      'fileNotExist': 'Файл не найден в хранилище',
      'speed05': '0.5x Медленно',
      'speed10': '1.0x Нормально',
      'speed20': '2.0x Быстро',
      'privacySettings': 'Настройки конфиденциальности',
      'privacySettingsDesc': 'Управляйте предпочтениями персонализации рекламы',
      'managePrivacy': 'Управление конфиденциальностью',
      'volume': 'Громкость',
      'everything': 'Всё',
      'favorite': 'Избранное',
      'simpleMode': 'Простой режим',
      'simpleModeDesc': 'Скрыть кнопки настроек и избранного на каждом звуке',
      'hideCategories': 'Скрыть категории',
      'hidePlayback': 'Скрыть плеер',
      'hapticFeedback': 'Вибрация',
      'backupRestore': 'Резервная копия',
      'backupRestoreDesc': 'Экспортируйте звуки или восстановите из резервной копии.',
      'exportSounds': 'Экспорт звуков',
      'importSounds': 'Импорт звуков',
      'toolbarButtons': 'Кнопки панели',
      'toolbarButtonsDesc': 'Выберите, какие кнопки отображаются на верхней панели',
      'darkMode': 'Тёмный режим',
      'supportTitle': 'Поддержать разработчика',
      'supportDesc': 'Если вам нравится приложение, угостите меня кофе!',
      'donateButton': 'Угостить кофе',
      'noCategoryTitle': 'Категория не выбрана',
      'noCategoryMessage': 'Этот звук будет отображаться только в «Всё». Добавить всё равно?',
      'addAnyway': 'Добавить всё равно',
      'volumeControl': 'Регулятор громкости',
      'displayOptions': 'Параметры отображения',
      'displayOptionsDesc': 'Выберите, что отображать на саундборде',
      'hideFavoriteButton': 'Скрыть кнопку избранного',
      'hideSettingsButton': 'Скрыть кнопку настроек',
      'fadeGlobalDescription': 'Глобальная настройка для всех звуков',
      'hideVolumeBar': 'Скрыть регулятор громкости',
      'exportSaved': 'Сохранено: ',
      'exportFailed': 'Ошибка экспорта: ',
      'importFailed': 'Ошибка импорта: ',
    },
    'ja': {
      'settings': '設定',
      'addSound': 'サウンドを追加',
      'addSoundDesc': 'サウンドボードにカスタムサウンドを追加',
      'loop': 'ループ',
      'shufflePlay': 'シャッフル再生',
      'playbackSpeed': '再生速度',
      'deleteMode': '削除モード',
      'cancelDeleteMode': '削除モードをキャンセル',
      'searchSounds': 'サウンドを検索...',
      'noSoundPlaying': '再生中のサウンドなし',
      'nowPlaying': '再生中:',
      'soundsCount': 'サウンド',
      'noSoundsFound': 'サウンドが見つかりません',
      'tryChangingSearch': '検索またはカテゴリを変更してください',
      'restoringSound': 'サウンドを復元中...',
      'pleaseWait': 'しばらくお待ちください',
      'resetSounds': 'サウンドをリセット',
      'resetSoundsDescription': '現在のすべてのサウンドが削除され、元のサウンドとカテゴリが再読み込みされます。',
      'resetToDefault': 'デフォルトサウンドにリセット',
      'resetConfirmTitle': 'サウンドをリセット',
      'resetConfirmMessage': '現在のすべてのサウンドが削除され、元のサウンドとカテゴリが再読み込みされます。\n\n続行しますか？',
      'cancel': 'キャンセル',
      'reset': 'リセット',
      'deleteAll': 'すべて削除',
      'deleteAllSounds': 'すべてのサウンドを削除',
      'deleteAllConfirmTitle': 'すべてのサウンドを削除',
      'deleteAllConfirmMessage': 'すべてのサウンドが完全に削除されます。この操作は元に戻せません。\n\n続行しますか？',
      'manageCategories': 'カテゴリを管理',
      'manageCategoriesDescription': '不要なカテゴリを削除します。このカテゴリを持つすべてのサウンドからカテゴリが削除されます。',
      'trimSound': 'サウンドをトリム',
      'trimReset': 'トリムをリセット',
      'trimLoading': '読み込み中...',
      'editCategory': 'カテゴリを編集',
      'newCategoryName': '新しい名前',
      'deleteCategory': 'カテゴリを削除',
      'deleteCategoryConfirm': '"{category}"を削除してもよろしいですか？\n\nこのカテゴリを持つすべてのサウンドからカテゴリが削除されます。',
      'deleteSoundsAlso': 'このカテゴリのすべてのサウンドも削除する',
      'delete': '削除',
      'noCustomCategories': 'カスタムカテゴリはまだありません',
      'language': '言語',
      'selectLanguage': '使用する言語を選択してください',
      'soundName': 'サウンド名',
      'categories': 'カテゴリ',
      'add': '追加',
      'newCategory': '新しいカテゴリ',
      'enterCategoryName': 'カテゴリ名を入力',
      'buttonColor': 'ボタンの色',
      'save': '保存',
      'addNewSound': '新しいサウンドを追加',
      'categoryName': 'カテゴリ名',
      'stopRecording': '録音を停止',
      'record': '録音',
      'play': '再生',
      'stop': '停止',
      'pickFile': 'ファイルを選択',
      'addCategory': 'カテゴリを追加',
      'saveSound': 'サウンドを保存',
      'filter': 'フィルター:',
      'search': '検索:',
      'soundsOnlyInEverything': 'カテゴリなしのサウンドは「すべて」にのみ表示されます',
      'errorDeletingSound': 'サウンド削除エラー:',
      'errorPlayingSound': 'サウンド再生エラー:',
      'fileNotExist': 'ストレージにファイルが存在しません',
      'speed05': '0.5x 低速',
      'speed10': '1.0x 標準',
      'speed20': '2.0x 高速',
      'privacySettings': 'プライバシー設定',
      'privacySettingsDesc': '広告のパーソナライズ設定を管理する',
      'managePrivacy': 'プライバシーを管理',
      'volume': '音量',
      'everything': 'すべて',
      'favorite': 'お気に入り',
      'simpleMode': 'シンプルモード',
      'simpleModeDesc': '各サウンドの設定とお気に入りボタンを非表示にする',
      'hideCategories': 'カテゴリを非表示',
      'hidePlayback': 'プレーヤーを非表示',
      'hapticFeedback': '振動',
      'backupRestore': 'バックアップと復元',
      'backupRestoreDesc': 'サウンドをファイルにエクスポートするか、以前のバックアップから復元します。',
      'exportSounds': 'サウンドをエクスポート',
      'importSounds': 'サウンドをインポート',
      'toolbarButtons': 'ツールバーボタン',
      'toolbarButtonsDesc': '上部ツールバーに表示するボタンを選択する',
      'darkMode': 'ダークモード',
      'supportTitle': '開発者を支援',
      'supportDesc': 'アプリを気に入っていただけたら、コーヒーをご馳走ください！',
      'donateButton': 'コーヒーをご馳走する',
      'noCategoryTitle': 'カテゴリなし',
      'noCategoryMessage': 'このサウンドは「すべて」にのみ表示されます。それでも追加しますか？',
      'addAnyway': 'それでも追加',
      'volumeControl': '音量コントロール',
      'displayOptions': '表示オプション',
      'displayOptionsDesc': 'サウンドボードに表示する内容を選択する',
      'hideFavoriteButton': 'お気に入りボタンを非表示',
      'hideSettingsButton': '設定ボタンを非表示',
      'fadeGlobalDescription': 'すべてのサウンドのグローバル設定',
      'hideVolumeBar': '音量バーを非表示',
      'exportSaved': '保存済み: ',
      'exportFailed': 'エクスポート失敗: ',
      'importFailed': 'インポート失敗: ',
    },
  };

  String get(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']![key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'pt', 'es', 'fr', 'de', 'it', 'id', 'ru', 'ja'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
