// Data version - zvýš toto číslo keď zmeníš defaultné zvuky
// Aplikácia automaticky resetuje zvuky pri zmene verzie
const int DATA_VERSION = 10;

// Sound file names - all MP3 files from assets folder
// AUTOMATICALLY GENERATED - DO NOT EDIT MANUALLY

final assetSoundFiles = [
  '01-oh-yeah.mp3',
  '1-000-000-000-iq.mp3',
  '2_hours_later.mp3',
  '2thousant_years_later.mp3',
  '3_2_1.mp3',
  '5nights_at_fredy.mp3',
  '67.mp3',
  'Chinese Phone Toy barbie Song.mp3',
  'action_sound.mp3',
  'affrican_music.mp3',
  'all-of-tf2-laughing-at-you-at-once.mp3',
  'amogus.mp3',
  'and_his_name_is_john_cena.mp3',
  'angry_indian.mp3',
  'anime-wow-sound-effect-mp3cut.mp3',
  'anime_running.mp3',
  'aplausos_3.mp3',
  'applause.mp3',
  'arabic_music.mp3',
  'arrr-pirates.mp3',
  'baby-laughing-meme.mp3',
  'balls_in_your_jaw.mp3',
  'bass.mp3',
  'batman_coming.mp3',
  'black_friends.mp3',
  'bomb-has-been-planted-sound-effect-cs-go.mp3',
  'brainrot.mp3',
  'bro_calling.mp3',
  'bruh.mp3',
  'buzzer.mp3',
  'cat-laugh-meme-1.mp3',
  'caveman_scream.mp3',
  'chilling_on_the_weekend.mp3',
  'china_song.mp3',
  'clash_royal_start.mp3',
  'clash_royala_laguh.mp3',
  'clown_trumpet.mp3',
  'computer_beep.mp3',
  'connected.mp3',
  'conversion_E5bEYlM.mp3',
  'cool_music.mp3',
  'crazy-realistic-knocking-sound-troll-twitch-streamers_small.mp3',
  'crazy_monkey.mp3',
  'crickets.mp3',
  'dah.mp3',
  'damn_son_where_you_find_this.mp3',
  'danika_house.mp3',
  'deez_nuts.mp3',
  'deja-vu.mp3',
  'deny.mp3',
  'dexter-song-2.mp3',
  'diarrhea.mp3',
  'did_you_pray_today.mp3',
  'didnt_have_to_cut_me.mp3',
  'directed-by-robert-b_voI2Z4T.mp3',
  'disconected.mp3',
  'discord-call-sound.mp3',
  'discord-notification.mp3',
  'dissapointment.mp3',
  'dobroe-utro-moia-devochka.mp3',
  'emotional_damage.mp3',
  'end_bell.mp3',
  'enemy_spotted.mp3',
  'engineer_autoattackedbyspy03.mp3',
  'engineer_cheers07.mp3',
  'enyoing_meal.mp3',
  'epic_fart.mp3',
  'epic_flex_sound.mp3',
  'epic_punch.mp3',
  'epic_reveal.mp3',
  'evil_morty.mp3',
  'explosion.mp3',
  'falling_scream.mp3',
  'fart1.mp3',
  'fbi_openup.mp3',
  'flex_sound.mp3',
  'french-meme-song.mp3',
  'funky.mp3',
  'gangsta_paradise.mp3',
  'gay-mp3.mp3',
  'get_out.mp3',
  'giga_chad.mp3',
  'go_crazy_go_stupid.mp3',
  'go_go_go.mp3',
  'god_damn.mp3',
  'goofy_ass_fall.mp3',
  'goofy_ass_sounds.mp3',
  'goofy_falling.mp3',
  'goofy_laugh.mp3',
  'gta-san-andreas-ah-shit-here-we-go-again_BWv0Gvc.mp3',
  'gta_kill.mp3',
  'gulp_gulp_gulp.mp3',
  'gunshotjbudden.mp3',
  'hamburger.mp3',
  'happy_kids.mp3',
  'happy_meal.mp3',
  'happy_music.mp3',
  'har_har_har.mp3',
  'he-hell-nah-dog.mp3',
  'heavy_medic02.mp3',
  'heavy_medic03_doctor.mp3',
  'helicopter_helicopter.mp3',
  'hell-yeah.mp3',
  'hell_nah.mp3',
  'hog_rider.mp3',
  'holy_afterlife.mp3',
  'homero-gimiendo.mp3',
  'howcouldthishappen.mp3',
  'huh.mp3',
  'huhh.mp3',
  'i-broke-your-stupid-crap-moron.mp3',
  'i_cant_hold_it_anymore.mp3',
  'i_like_your_cut_g.mp3',
  'i_was_never_there_rizz3.mp3',
  'if_we_beeing_real.mp3',
  'im_innocent_sound.mp3',
  'im_under_the_water.mp3',
  'imbo.mp3',
  'indian-christmas-2-0.mp3',
  'indian-jingle-bells.mp3',
  'indian_song.mp3',
  'iphone_ringtone.mp3',
  'italian-brainrot-ringtone.mp3',
  'john_cena_in_china.mp3',
  'jupi.mp3',
  'kid_crying_autotune.mp3',
  'knock_knock.mp3',
  'laugh_in_vent.mp3',
  'lego-breaking.mp3',
  'lego_break.mp3',
  'let-me-know.mp3',
  'let_him_cook.mp3',
  'let_me_do_it_for_you.mp3',
  'lion_king.mp3',
  'lobotomy-sound-effect.mp3',
  'lol-limewire.mp3',
  'low_ft_t.mp3',
  'm-e-o-w.mp3',
  'mad_monkey.mp3',
  'match_beggining.mp3',
  'medics-answer-to-every-question-in-the-universe.mp3',
  'meemstart.mp3',
  'meet-the-spy-sound.mp3',
  'megalovania.mp3',
  'meme-okay-lets-go.mp3',
  'metal_pipe.mp3',
  'mi-bombo-duolingo.mp3',
  'minecraft_eating.mp3',
  'minion_hello.mp3',
  'mission_completed.mp3',
  'mr-krabs.mp3',
  'mr_beast.mp3',
  'my-movie.mp3',
  'my_name_is_scarlet_white.mp3',
  'mylongestyeahboyever.mp3',
  'nani.mp3',
  'neck_break.mp3',
  'never_gonna_give_you_up.mp3',
  'ngakak-laugh-annoying.mp3',
  'no-god-please-no-noooooooooo.mp3',
  'nokia_ringing.mp3',
  'nooo.swf.mp3',
  'nope.mp3',
  'number-one-victory-royale-yeah-fortnite-we-bout-to-get-down.mp3',
  'oh-my-god-bruh-ah-hell-no.mp3',
  'oh-no-no-no-no-laugh.mp3',
  'oh_god_heavens.mp3',
  'oh_yeahh.mp3',
  'ohio_athem.mp3',
  'open_the_door.mp3',
  'people_laugh.mp3',
  'phonk.mp3',
  'phonk2.mp3',
  'pirates-of-the-caribbean-theme-song.mp3',
  'prowler-sound-effect.mp3',
  'pull_up_to_the_pary.mp3',
  'punch-sound-effect-meme.mp3',
  'rehehehe.mp3',
  'reveal_music.mp3',
  'ringtone.mp3',
  'riz1.mp3',
  'rizz.mp3',
  'rizz2.mp3',
  'roblox_mnam.mp3',
  'romanceeeeeeeeeeeeee.mp3',
  'romantic_saxofone.mp3',
  'ronaldo.mp3',
  'run-vine-sound-effect.mp3',
  'saaaaaa100.mp3',
  'sad-meow-song.mp3',
  'sad.mp3',
  'sad_trombone.mp3',
  'samuraj_preparation.mp3',
  'sawg_like_ohio.mp3',
  'scooby_doo_laught.mp3',
  'scout-tf2-wananana.mp3',
  'scream_freddy.mp3',
  'screaming-scout.mp3',
  'screaming-soldier-tf2.mp3',
  'shocked-sound-effect.mp3',
  'shut-your-mouth-syfm.mp3',
  'shut_up.mp3',
  'sin_city.mp3',
  'siren.mp3',
  'sitcom-laughing-1.mp3',
  'skibidi_dop_yes.mp3',
  'slap.mp3',
  'smoke-detector-beep.mp3',
  'smokeweed.mp3',
  'sneaky-golem.mp3',
  'snooring_extreme.mp3',
  'snore_2.mp3',
  'somedy_shitted_his_pants.mp3',
  'sonic-exe-laugh.mp3',
  'sore_1.mp3',
  'sound-9______.mp3',
  'spiderman.mp3',
  'spongebob_failure.mp3',
  'spongebob_failure_2.mp3',
  'spongebob_how_are_you.mp3',
  'spookypiano.mp3',
  'squirel_laugh.mp3',
  'super_mario_death.mp3',
  'sus_amogus_sound.mp3',
  'sus_amogus_sound_2.mp3',
  'sus_impostor.mp3',
  'sus_sound.mp3',
  'sweet_home_alabama.mp3',
  'tate_song.mp3',
  'tf2-demoman-charge-sound-2.mp3',
  'tf2-heavy-om-nom-nom-sound-effect.mp3',
  'tf2-right-behind-you.mp3',
  'tf2-spy-peekaboo-sound-effect.mp3',
  'tf_domination.mp3',
  'tf_nemesis.mp3',
  'that_time.mp3',
  'thats_racist.mp3',
  'thomas-the-train-bass-boosted.mp3',
  'thomas-the-train-smoking-weed-meme-1.mp3',
  'titanic.mp3',
  'to_be_continued.mp3',
  'travis.mp3',
  'trembling_sound_effect.mp3',
  'truck_beep.mp3',
  'tung_sahur.mp3',
  'ultimate_idk.mp3',
  'undertakers-bell.mp3',
  'uwu.mp3',
  'victory-tf2.mp3',
  'visit_your_mother.mp3',
  'vizg-svini.mp3',
  'waitwait.mp3',
  'walk_to_poland.mp3',
  'wanna-see-a-magic-trick-tf2.mp3',
  'we-are-charlie-kirk-song.mp3',
  'western.mp3',
  'what-are-you-doing-in-my-swamp-.mp3',
  'what-oh-hell-no-grandpa.mp3',
  'what_a_sigma.mp3',
  'what_are_those.mp3',
  'what_the_dog_doin.mp3',
  'what_up_guys.mp3',
  'whip.mp3',
  'why_are_you_gay.mp3',
  'why_are_you_running.mp3',
  'why_you_bullying_me.mp3',
  'wii_sport_meme.mp3',
  'windows_error.mp3',
  'windows_restart.mp3',
  'woke_up_in_the_new_buggati.mp3',
  'wow.mp3',
  'yay_yay_yay.mp3',
  'yeah-boiii-i-i-i.mp3',
  'yeah-boymp4.mp3',
  'yo-ho-pirate-song.mp3',
  'yooooooooooooooooooooooooo_4_objp8XX.mp3',
  'you-are-dead-not-big-surprise-sound-effect.mp3',
  'you_are_not_fine.mp3',
  'you_kinda_smell.mp3',
  'your-phone-is-ringing-pick-it-up-now.mp3',
];


// Mapa kategórií pre každý zvuk
final Map<String, List<String>> soundCategories = {
  // ========== MEME ZVUKY ==========
  '01-oh-yeah.mp3': ['meme'],
  '1-000-000-000-iq.mp3': ['meme'],
  'amogus.mp3': ['meme', 'game'],
  'emotional_damage.mp3': ['meme'],
  'giga_chad.mp3': ['meme'],
  'bruh.mp3': ['meme'],
  'oh-my-god-bruh-ah-hell-no.mp3': ['meme'],
  'deez_nuts.mp3': ['meme'],
  'thats_racist.mp3': ['meme'],
  'hell-yeah.mp3': ['meme'],
  'hell_nah.mp3': ['meme'],
  'he-hell-nah-dog.mp3': ['meme'],
  'what-oh-hell-no-grandpa.mp3': ['meme'],
  'no-god-please-no-noooooooooo.mp3': ['meme'],
  'nope.mp3': ['meme'],
  'skibidi_dop_yes.mp3': ['meme'],

  // ========== MUSIC ==========
  'megalovania.mp3': ['music', 'game'],
  'gangsta_paradise.mp3': ['music'],
  'phonk.mp3': ['music'],
  'phonk2.mp3': ['music'],
  'pirates-of-the-caribbean-theme-song.mp3': ['music'],
  'yo-ho-pirate-song.mp3': ['music'],
  'sweet_home_alabama.mp3': ['music'],
  'never_gonna_give_you_up.mp3': ['music', 'meme'],
  'indian_song.mp3': ['music'],
  'indian-christmas-2-0.mp3': ['music'],
  'indian-jingle-bells.mp3': ['music'],
  'arabic_music.mp3': ['music'],
  'affrican_music.mp3': ['music'],
  'titanic.mp3': ['music'],
  'evil_morty.mp3': ['music'],
  'romantic_saxofone.mp3': ['music'],
  'western.mp3': ['music'],
  'dexter-song-2.mp3': ['music'],
  'to_be_continued.mp3': ['music', 'meme'],
  'lion_king.mp3': ['music'],

  // ========== GAME ZVUKY ==========
  'minecraft_eating.mp3': ['game', 'sound effects'],
  'roblox_mnam.mp3': ['game'],
  'clash_royal_start.mp3': ['game'],
  'clash_royala_laguh.mp3': ['game'],
  'hog-rider.mp3': ['game', 'meme'],
  'gta_kill.mp3': ['game', 'sound effects'],
  'gta-san-andreas-ah-shit-here-we-go-again_BWv0Gvc.mp3': ['game', 'meme'],
  'bomb-has-been-planted-sound-effect-cs-go.mp3': ['game'],
  'number-one-victory-royale-yeah-fortnite-we-bout-to-get-down.mp3': ['game', 'meme'],
  'super_mario_death.mp3': ['game'],
  '5nights_at_fredy.mp3': ['game'],

  // TF2 zvuky
  'tf2-demoman-charge-sound-2.mp3': ['game'],
  'tf2-heavy-om-nom-nom-sound-effect.mp3': ['game'],
  'tf2-right-behind-you.mp3': ['game'],
  'tf2-spy-peekaboo-sound-effect.mp3': ['game'],
  'tf_domination.mp3': ['game'],
  'tf_nemesis.mp3': ['game'],
  'all-of-tf2-laughing-at-you-at-once.mp3': ['game', 'meme'],
  'engineer_autoattackedbyspy03.mp3': ['game'],
  'engineer_cheers07.mp3': ['game'],
  'heavy_medic02.mp3': ['game'],
  'heavy_medic03_doctor.mp3': ['game'],
  'medics-answer-to-every-question-in-the-universe.mp3': ['game'],
  'meet-the-spy-sound.mp3': ['game'],
  'scout-tf2-wananana.mp3': ['game'],
  'screaming-scout.mp3': ['game'],
  'screaming-soldier-tf2.mp3': ['game'],
  'victory-tf2.mp3': ['game'],
  'wanna-see-a-magic-trick-tf2.mp3': ['game'],
  'you-are-dead-not-big-surprise-sound-effect.mp3': ['game'],

  // ========== SOUND EFFECTS ==========
  'explosion.mp3': ['sound effects'],
  'fart1.mp3': ['sound effects'],
  'epic_fart.mp3': ['sound effects'],
  'metal_pipe.mp3': ['sound effects', 'meme'],
  'slap.mp3': ['sound effects'],
  'punch-sound-effect-meme.mp3': ['sound effects'],
  'epic_punch.mp3': ['sound effects'],
  'applause.mp3': ['sound effects'],
  'aplausos_3.mp3': ['sound effects'],
  'bass.mp3': ['sound effects'],
  'clown_trumpet.mp3': ['sound effects'],
  'sad_trombone.mp3': ['sound effects'],
  'buzzer.mp3': ['sound effects'],
  'windows_error.mp3': ['sound effects'],
  'computer_beep.mp3': ['sound effects'],
  'smoke-detector-beep.mp3': ['sound effects'],
  'truck_beep.mp3': ['sound effects'],
  'siren.mp3': ['sound effects'],
  'action_sound.mp3': ['sound effects'],
  'epic_reveal.mp3': ['sound effects'],
  'reveal_music.mp3': ['sound effects'],
  'lego_break.mp3': ['sound effects'],
  'lego-breaking.mp3': ['sound effects'],
  'neck_break.mp3': ['sound effects'],
  'whip.mp3': ['sound effects'],
  'knock_knock.mp3': ['sound effects'],
  'crazy-realistic-knocking-sound-troll-twitch-streamers_small.mp3': ['sound effects'],
  'discord-call-sound.mp3': ['sound effects'],
  'discord-notification.mp3': ['sound effects'],
  'iphone_ringtone.mp3': ['sound effects'],
  'nokia_ringing.mp3': ['sound effects'],
  'ringtone.mp3': ['sound effects'],
  'your-phone-is-ringing-pick-it-up-now.mp3': ['sound effects', 'meme'],
  'windows_restart.mp3': ['sound effects'],
  'connected.mp3': ['sound effects'],
  'disconected.mp3': ['sound effects'],
};

// Helper function for color generation
String _colorFromLightness(int index, int total) {
  return '#FF7BAFD4';
}

// Automatically generated list of default sounds
final List<Map<String, dynamic>> defaultSounds =
List<Map<String, dynamic>>.generate(assetSoundFiles.length, (index) {
  final fileName = assetSoundFiles[index];
  final title = fileName.replaceAll('.mp3', '').replaceAll('_', ' ');

  return {
    'name': fileName,
    'title': title,
    'categories': soundCategories[fileName] ?? <String>[],
    'fav': false,
    'color': _colorFromLightness(index, assetSoundFiles.length),
  };
});
